### ISSUE TITLE
Set up migration scripts to evolve the database schema after 1.0.0

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#10]
In GitLab by @kevinbader on May 22, 2018, 17:22

**Comment by phpai** [comment]
In GitLab by @Stezido on Jan 7, 2019, 10:51

should be solved by this [adr](https://innersource.stackato.de/trubudget/trubudget-app/blob/master/doc/adr/0010-multi-node-setup.md).
@kevinbader Am I right?

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 25, 2019, 10:59

I think that this issue is more about how to migrate data from one installation to another one in case of a major/breaking change of the on-chain data format. In other words, if the change is not backward-compatible, all data has to be translated/lifted into the newer format. Usually, people don't expect to do something like this manually, so we have to make sure there is a strategy for that. @gonzochic what exactly do we need to prepare in advance?

**Comment by gonzochic** [comment]
Since we currently don't have the need for a database migration functionality we can close the issue for now.
