### ISSUE TITLE
Rename user.list to identity.list + add user.list v2 that returns users only

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#101]
In GitLab by @kevinbader on Mar 6, 2019, 08:10

The current user.list API returns *identities*, that is, groups in addition to users. A more consistent approach would be to introduce a new identity.list endpoint with the same behaviour, while evolving user.list to a new version that no longer returns groups.

**Comment by kevinbader** [comment]
API change => scheduled for 2.x
