### ISSUE TITLE
Failed to grant authorizations to the "external readers" group

### ISSUE THREAD

**Issue by FlorenceBE** [openkfw/TruBudget#1053]
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

In TruBudget’s sandbox, using the French version for Burkina Faso on March 15th, 2022, I tried to add the “Lecteur externe” (i.e. external readers) group to the users allowed to see the workflow item named “Guide utilisateur” in the only component (called “Guides d’utilisation”) of the project called “Aide aux utilisateurs”. I also tried to add the “Lecteur externe” (i.e. external readers) group to the users allowed to see the authorizations for this workflow item.
Once I click “confirm”, the message « failed to share document X to organization KfW: could not get secret for document X and organization KfW: not found: secret X » appears. 

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/101820761/158849824-d87bdb0c-4b7c-4dbf-9a1d-2720a4293ce6.png)

| Windows 10 for Business | 20H2 |
| --------------- | ------- |
| Frontend        | v1.?.?  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by georgimld** [comment]
Hello @FlorenceBE, this can also be explained by [this](https://github.com/openkfw/TruBudget/issues/1054#issuecomment-1074157988).

**Comment by georgimld** [comment]
@FlorenceBE we managed to find out why this happens, there is a bug with document sharing in our code. 

We will create a hotfix with a fix for this!
