### ISSUE TITLE
Failed to create a workflow item with an attached document

### ISSUE THREAD

**Issue by FlorenceBE** [openkfw/TruBudget#1054]
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

In TruBudget’s sandbox, using the French version for Burkina Faso on March 15th, 2022, I tried to create a new workflow item in the component named “Livrables” in the project “SIGFE”, with our last quarterly report attached to it as a pdf document. Once I clicked “confirm”, the message « failed to store document: upload object failed: storage service error » appeared. I was using the robot user "Créé automatiquement". The attached document’s size was below 1400 Ko. On the same day, using the same robot user in the same component of the same project, I had successfully created other workflow items, with or without documents attached. 

Here is a screenshot of the error: 
![image](https://user-images.githubusercontent.com/101820761/158855148-61cfe4fa-1abe-4ac7-b083-489738788aa1.png)

| Windows 10 for Business | 20H2 |
| --------------- | ------- |
| Frontend        | v1.?.?  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by georgimld** [comment]
Hello @FlorenceBE , it looks like ypur storage service is enabled (via `DOCUMENT_FEATURE_ENABLED` environment variable in the api) but is not working. Please check if the storage-service and minio containers are running

**Comment by georgimld** [comment]
Hi @FlorenceBE, I managed to reproduce your error, this happens because your minio instance is down. So make sure it is started and your storage service can connect to it and then you should have no more problems.

**Comment by georgimld** [comment]
@FlorenceBE We checked the errors on our side and it turns out minio does return an error while uploading documents, because it does not support some special characters in the document name, including french accent characters. 

We will work on a fix to be able to avoid this issue in the future!
