### ISSUE TITLE
Possibility to Upload docs with size above 70mb

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1062]
### Discussed in https://github.com/openkfw/TruBudget/discussions/853

<div type='discussions-op-text'>

<sup>Originally posted by **a-dossa** October 21, 2020</sup>
At the workflow item level, giving the possibility to upload documents which size are above 70mb

</div>

**Comment by SamuelPull** [comment]
There is a magical constant `app.use(express.json({ limit: "75mb" }));`
