### ISSUE TITLE
Allow user to add sub project attributes when adding a new sub project

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#107]
In GitLab by @lennart.ploen on Mar 6, 2019, 18:04

**Objective**: Add additional data fields in the window "add new subproject" and allow the user to change the order of subprojects in the list

**Purpose**: A project may have a large amount of contracts with subcontractors to be displayed on TruBudget. For example, a project financed through KfW and managed through the fonds FICOD in Burkina Faso, finances subprojects in 32 different communities, and five different contracts with service providers are realized in each community. This would mean 160 sub projects for this project in TruBudget. Changing the order of subprojects and adding data fields to be entered when adding a subproject may allow to search/filter for a specific subproject by searching for subproject attributes, and automate processes on TB

**Concept**:

- Allow to change the order of subprojects in the list of subprojects (for example, user might prefer to see open subprojects on top of the list)
- Add a search function to the subproject level, similar to the search function on the project level (see issue 371)
- Add an additional field when creating a subproject "attributes". This should be an open answer field (like the comment field), but the user should be instructed to enter data in order to facilitate the search function ("For a large number of subprojects, please define attributes for each subproject in order to facilitate searching for a subproject. For example, enter the name of the community, the name of the subcontractor, the type of subcontractor, the name of the operational component as fixed in the financing convention, or similar").
- Add an additional field when creating a subproject "subproject code" : This field is particularly meant for identifying the code of a signed contract with a subcontractor. It allows to search for this contract, but also to identify the subproject and automate workflow item creation/closure through an interface with the existing software in Burkina Faso.

Note that when projects are co-financed (State + Donor and/or multiple donors), a subproject can be financed through multiple sources. If TruBudget should be able to track expenses per source of financing, then a subproject needs to distinguish sources of financing in a similar way as proposed on project level (see issue 373).

Representation in the UI : Meta data (sub project code, sub project attributes), budget distribution and sources of finance can be accessible and represented in the UI in a similar way as on the project level (see issue 385).

[190306_subprojects.pptx](https://github.com/openkfw/TruBudget/files/3002299/190306_subprojects.pptx)

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 8, 2019, 11:25

changed the description

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 18, 2019, 10:19

changed the description

**Comment by mathiashoeld** [comment]
Additional data is currently only an API feature and should not be edited via the frontend. Closing the issue.
