### ISSUE TITLE
check for open TODOs in code

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1070]
## Description 💡

Check for open TODO comments in all services, make sure they are resolved

Split into 2 parts:
- Trubudget 2.x Todos #1112 
- Trubudget 1.x Todos #1129

**Comment by daniel-arnauer** [comment]
some ToDos:

- remove `.viewSummary` in intents.ts and everywhere else
- change workflowitem rejected reason and workflowitem status (open, closed)
