### ISSUE TITLE
Add functional metrics on numbers users, projects etc. to the API

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1071]
### Discussed in https://github.com/openkfw/TruBudget/discussions/875

<div type='discussions-op-text'>

<sup>Originally posted by **phpai** August 16, 2019</sup>
Add additional functional metrics to the /metrics endpoint, e.g.

- Number of users
- Number of projects
- ...</div>

**Comment by jzakotnik** [comment]
Nice idea but for the moment not needed
