### ISSUE TITLE
Due Date Entry - no date saved when manually typed into the due date field

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1081]
- [ x ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
Due date entry is only possible from the calendar. The field does allow teh enter date mnaually, but it is not saved. 

### How to reproduce 🕹
Enter manually due date on a WF Item. It is saved as null, even though the format of the date is correct.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.28.1  |
| API             | v1.28.1  |
| Blockchain      | v1.28.1  |
| Export-Service  | v1.28.1  |
| Email-Service   | v1.28.1  |
| Storage-Service | v1.?.?  |

**Comment by daniel-arnauer** [comment]
Thanks for finding this issue. It will be fixed in #1080 and the next release
