### ISSUE TITLE
Due Date Entry - previous day inserted

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1082]
- [ x ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
When selecting a due date from the calendar, e.g. 28.11.2021, the previous 27.11.2021 (Day - 1) is entered into the Due date field. 

### How to reproduce 🕹
When selecting a due date from the calendar, e.g. 28.11.2021, the previous 27.11.2021 (Day - 1) is entered into the Due date field. 
Likely related to the regional setting of the user?

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.28.1  |
| API             | v1.28.1  |
| Blockchain      | v1.28.1  |
| Export-Service  | v1.28.1  |
| Email-Service   | v1.28.1 |
| Storage-Service | v1.?.?  |

**Comment by daniel-arnauer** [comment]
Thanks for finding this issue. It will be fixed in #1080 and the next release
