### ISSUE TITLE
Show additional data/indicators on project level UI

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#109]
In GitLab by @lennart.ploen on Mar 7, 2019, 14:50

**Objective**: Add new data fields and indicators in the UI of the project level.

**Purpose**: Allow user to distinguish financing sources, access financial execution indicator and other project meta data attributes

**Concept**: 

The following data should be shown in the upper part of the UI on project level:
- Total budget
- Budget per source of finance (see issue 334)
- Proejcted budget
- Assigned budget
- Disbursed budget 

See attachments for details and definitions.

The following data should be made visible by pushing the meta data button (see issue 368 and 373) : project code, financing contract code(s), managing structure, action, activity, programme budgétaire.

For simplicity and in line with local applications, all amounts should be expressed in local currency. This is particularly relevant for co-financed projects with different currencies (e.g. € and local currency, a typical combination when the state co-finances part of the project) which need to be translated into one common currency in order to calculate the total. If the original amount is not the local currency, we propose that the amount is also displayed in the original currency.

[190318_Budgets.xlsx](https://github.com/openkfw/TruBudget/files/3002290/190318_Budgets.xlsx)

[190307_UI_projects.pptx](https://github.com/openkfw/TruBudget/files/3002291/190307_UI_projects.pptx)

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 18, 2019, 10:09

changed the description

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 18, 2019, 14:11

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 15:28

changed the description

**Comment by kevinbader** [comment]
closed by #202
