### ISSUE TITLE
Test all components with unit tests

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1090]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

For some componpents we already implemented unit test.
The goal is to implement unit tests in each component and for each case at least 1 positiv and 1 negative., so that we at least cover each file if possible and if it makes sense

Discussion-reference: <Insert discussion reference here>

**Comment by galethil** [comment]
Already implemented, closing.
