### ISSUE TITLE
Frozen pop-up after permission

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1105]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
When giving permissions to a group (probably on workflowitem level), the pop-up remains frozen after clicking "Confirm", the only way to exit the pop-up is to click on "Cancel", as seen in the screenshot below:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/48566702/163383305-0bd75a0c-c802-4cba-b897-ee71537c7d0a.png">

However, after clicking cancel and checking, it was noticed that the permission granting actually worked. 
So the problem probably is that the "Confirm" button doesn't trigger a confirmation message and doesn't close the pop-up.

### How to reproduce 🕹

To reproduce the bug you need to force the frontend to return an error, for example by going to `frontend/src/sagas.js` in the function `assignProjectSaga` and adding `throw new Error();` in the `try`block  - don't forget to remove this once the fix is done!

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.28.1  |
| API             | master  |
| Blockchain      | v1.28.1   |
| Export-Service  | v1.28.1   |
| Email-Service   | v1.28.1   |
| Storage-Service | v1.28.1  |

**Comment by daniel-arnauer** [comment]
How to reproduce in UI:

Go to `api/src/project_assign.ts` and change `const code = 200;` to `const code = 404;`

Then got to frontend and try to assign a user to a project
