### ISSUE TITLE
Inconsistent JSON format

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#111]
In GitLab by @thomas.anderl on Mar 8, 2019, 10:26

The response on the API for projects and subprojects, both provide the caller with following format:
```
{
...
 "data":{
  "items": [
   ...
  ]
 }
}
```

When querying for workflow items (workflowitem.list), the structure is slightly different:
```
{
...
 "data":{
  "workflowitems": [
   ...
  ]
 }
}
```

This leads to a different structure when retreiving the data and a uniform datastructure to serialize the data is no longer possible.

**Comment by mathiashoeld** [comment]
@Stezido was this already fixed?

**Comment by kevinbader** [comment]
@mathiashoeld @gonzochic this would change the API. I think I'd postpone this to the 2.x release - thoughts?

**Comment by jzakotnik** [comment]
Stale issue, doesn't seem that relevant
