### ISSUE TITLE
Show Who uploaded document

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#113]
In GitLab by @lennart.ploen on Mar 11, 2019, 10:34

Purpose: As the user is unable to see the content of an uploaded document, she should be able to see who uploaded the document she is supposed to validate. If the document validation is "not ok", she should be able to contact the uploader of the original document to discuss the issue. If this is not to happen on TB, at least the name + contact details of the uploader should be available on TB.

**Comment by mathiashoeld** [comment]
adding a document produces a history entry, as of #85. closing this issue.
