### ISSUE TITLE
Make the validation of an uploaded document mandatory for the closure of a workflow item or show the outstanding validation of a document for a closed workflow item

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#115]
In GitLab by @lennart.ploen on Mar 11, 2019, 12:22

Currently, a document can be validated (or not) at any time (before or after closure of workflow item). If there is a document, the assignee of a workflow item should be obliged to validate the document before closure of the workflow item. Only then the validation of a document becomes meaningful as it garantees that both parties dispose of the same document at the moment of workflow item closure. The validation of the document necessarry for workflow item closure should only be done by the assignee. Alternatively, a more flexible solution would be to be able to close a workflowitem without validating the document, but the outstanding validation of the document should be highlighted in a comment (For example "Document not yet validated by assignee")

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 17:21

Link with issue 395

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 17:24

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 15:27

changed the description

**Comment by mathiashoeld** [comment]
Not all documents need validation before workflow item is closed. The validation should be used to check whether a document has been modified **after** a workflow item has been closed.
