### ISSUE TITLE
Automate Sonarqube or Sonarcloud

### ISSUE THREAD

**Issue by daniel-arnauer** [openkfw/TruBudget#1160]
## Description 💡
Add a way to run Sonarqube or Sonarcloud automatically

Usefull links:
https://docs.sonarcloud.io/advanced-setup/automatic-analysis/

Relates to #1091  an #1100

**Comment by SamuelPull** [comment]
I think we can close this. I'm missing an explanation why one of these two particular tools should be incorporated.
