### ISSUE TITLE
Code docs in entire api

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1164]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Follow up of issue #1087 and PR #1118, code docs must be implmeneted in all api folders.
- [ ] all folders in http layer (functions, interfaces, constants, etc)
- [ ] service layer (functions, interfaces, constants, etc)
- [x] domain layer (functions, interfaces, constants, etc)

**Comment by Stezido** [comment]
Domain layer functions are documented already.
Service and http layer still open
