### ISSUE TITLE
Remove peer deps in frontend

### ISSUE THREAD

**Issue by daniel-arnauer** [openkfw/TruBudget#1166]
## Description 😯
`@mui/styles@5.8.0` and `connected-react-router` are not compatible with React 18:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @mui/styles@5.8.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.9.0
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.8.2" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.8.1
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.8.1" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!   22 more (@emotion/styled, @mui/base, @mui/icons-material, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @mui/styles@5.8.0
npm ERR! node_modules/@mui/styles
npm ERR!   @mui/styles@"^5.5.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0" from @mui/styles@5.8.0
npm ERR!   node_modules/@mui/styles
npm ERR!     @mui/styles@"^5.5.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### How to reproduce 🕹
Run `npm install` in frontend

### Solution
- [ ] wait for updates in connected-react-router
- [x] remove @mui/styles

**Comment by SamuelPull** [comment]
connected-react-router will most probably not be updated https://github.com/supasate/connected-react-router/issues/613

**Comment by SamuelPull** [comment]
Closing, as most of frontend libraries are up to date, and `--legacy-peer-deps` is no longer needed.
