### ISSUE TITLE
Add workflow item code when creating workflow item

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#117]
In GitLab by @lennart.ploen on Mar 12, 2019, 12:29

**Objective**: Add workflow item code when creating workflow item

**Purpose**: 
The identification of a workflow item is important a) for the user ("which payment are we talking about?") and b) for the automatisation of workflow item creation/closure via an interface with existing applications (communication between CIFE/SIMP and TB). Examples include:
- Call for tender --> Need tender code
- Selection of subcontractor --> Need tender code
- Signature of contract --> Need contract code
- Financial allocation through financing agreement --> Need code of financing agreement
- Payment request --> Need code of payment request

**Concept**:
Create an additional data field at the moment of workflow item creation called "code of workflow item" (optional data entry as not essential for every workflow item). 
Once the workflow item has been created, this code should be shown in brackets at the end of the name of the workflow item in the list of workflow items (see examples in red in the attached slide). Note that all of these codes exist in existing software (CIFE / SIMP) - Once TB is integrated with existing tools, this field can be filled in automatically.

[190312_workflow_item_creation.pptx](https://github.com/openkfw/TruBudget/files/3002287/190312_workflow_item_creation.pptx)

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 11:00

This sounds very specific to the Burkina case and will eventually replaced by an API call anyway (note that the API itself already provides the "additionalData" object for this purpose). @jzakotnik what are your thoughts on this API change - do you think this could be relevant for other users as well?

**Comment by gonzochic** [comment]
We could solve this using tagging (see #157). This means we could add a tag with the tender or contract code. The tag would be visible, you can query it and you would also be able to search for it. This feature is not implemented but in the backlog.
