### ISSUE TITLE
Document download from different node or orga -SP 4

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1192]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

It is currently not possible to download a document if the document feature is disabled on own node, but the node wants to download documents from a different node or orga.

-  This must be fixed on frontend side (the document tab in workflowitem details modal should not be disabled if own document storage is not available)
- On api side, download from other orga even if own document storage is not enabled (this must be checked)

### How to reproduce 🕹
Start two nodes, one with one without document feature enabled. The node with the doc feature should upload a document and the node without should try to download that document.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| TruBudget        | v2.0.0  |

**Comment by Stezido** [comment]
TODOs:
- api: don't check for own storage service only but check if the document is of another organization
- frontend: Enable document download tab
