### ISSUE TITLE
Don't resolve user info using user.list calls; instead, add user info to API responses

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#12]
In GitLab by @kevinbader on May 28, 2018, 08:39

Instead of the additional calls to `user.list`, the API responses should carry the user information with it (organization, displayName).

**Comment by phpai** [comment]
In GitLab by @kevinbader on May 28, 2018, 08:39

@gonzochic fyi

**Comment by mathiashoeld** [comment]
similar to #101 - can possibly be fixed together
