### ISSUE TITLE
Patterns are too restrictive for names of projects/workflowitems SP1

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1202]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
the pattern for displayName in project and workflowitem (and probably also subproject) is too restrictive. 
In particular, some orthographic characters are missing, such as:

-  the en dash (–), 
- orthographic quotation marks (»«„“”''''), but also 
- the space without a break (&nbsp; in HTML). 

Possibly a Unicode RegExp could help here, e.g.: /^([\p{L}\p{N}\p{P}\p{M}\p{S}\p{Zs}]*)$/ and This would also be helpful to be able to use TruBudget with other writing systems (Arabic, Hebrew, Amharic, Farsi, ...) that are covered by these Unicode classes.

### How to reproduce 🕹
Try to create a project or workflowitem with the above mentioned characters

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| TruBudget        | v2.0.0  |

**Comment by schoel-bis** [comment]
The Regexp that you eventually came up with has at least one issue: It exludes the `Ps` and `Pe` classes and all the various types of braces and brackets are part of these. Some bracket types were included in the previous Regexp, e.g. () and [].

Second, I wonder what the idea behind this Regexp is in the first place. If it is meant to sanitize things or consumption in HTML (although I hope it is not), then please note that `<>` are included in the `S` (more specifically: `Sm`) class and `&` is in `Po`, both of which are allowed by the Regexp.
