### ISSUE TITLE
Default currency in dashboard view

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1228]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡
Add the possibility to define on user level default currency, in which dashboards are displayed. 
For countries that do not use EUR currency, the dashboard infromation needs to be switched into the local currency each time dashboards are consulted.

**Comment by sash9696** [comment]
Hi, @LukasKM @daniel-arnauer  Could you please assign this issue to me.

**Comment by mayrmartin** [comment]
Hey, @sash9696 glad to have you on board! 😃  Feel free to contribute to this issue and open a PR & assign me as a reviewer once you are finished. If you have any questions feel free to comment in this thread. We appreciate your help!

**Comment by galethil** [comment]
Hi @sash9696 do you need any help or support regarding this issue implementation? Are you still planning to work on it?

**Comment by jzakotnik** [comment]
@galethil I would propose to close this and focus on a guide how to connect Excel PowerQuery or PowerBI to TruBudget with respective templates.

**Comment by galethil** [comment]
@jzakotnik is there a requirement for Excel PowerQuery or PowerBI connection? Should we include it in the backlog as code spike or a prototype?

**Comment by jzakotnik** [comment]
@galethil users are typically asking for the analytics of the budgets etc. The analytics page in TB is a bit of a dead end because we can't offer the same features as a true analytics software. So the idea was to offer a guide how to connect to Excel, because this is mostly used by many people. Could be a code spike and isolated from the sprints.
