### ISSUE TITLE
Currency Management - activate or deactivate currencies applicable for the implementation context

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1229]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡
TruBudget supports FX rates from ECB that are available via an API. In contexts, where the ECB rates are not used, the conversions between EUR and local currency provides inacurate information. E.g. in KfW projects, the FX rate would be typically determined as a conversion rate from the disbursement. In addition, currencies that do not use the ECB API do not have the possiblity to update the FX rate. 

It would be good to allow a possibility to activate/deactivate currencies to control what currencies (in addition to the local currency) can the users consult.

**Comment by daniel-arnauer** [comment]
Relates to https://github.com/openkfw/TruBudget/issues/1154
