### ISSUE TITLE
Improve workflow item details and workflow item buttons, especially document validation, as well as the history function

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#123]
In GitLab by @lennart.ploen on Mar 12, 2019, 17:19

- Rename "workflow details" -> "workflow item details"
- Currently, the document validation button is hidden within the workflow item details. Instead, a button (for example paper clip symbol to represent "attachment") could be introduced on the right hand side of the workflow item showing in a more prominent way that a document needs to be validated before closure of the workflow item (see issue 390). This paper clip should only appear if there is a document to validate. Clicking the paper clip should show the document name, who uploaded it and when, and allow to validate the document. The fingerprint is not meaningful to the user (and currently not fully shown in the UI), so of no use to the user and does not need to be shown.
- As already done on project and subproject level, take off the buttons "edit" and "set permissions" on workflow item level, if the user does not have the permission to edit or set permissions. This will lighten the user interface. 
- Except for the uploaded document, the current workflow item details repeat information that is already accessible on the screen (title, assignee, budget, status of workflow item). Instead of this information, the details should show the following information:
1. Workflow item code (see issue 391)
2. History of changes for this workflow item, notably (a) who created the item and associated budget  + when, (b) who uploaded a document + when, (c) who validated the document + when. This information is particularly relevant (and not very accessible in the current long history flow) especially when there is an issue (document "not ok", assignee not willing to approve workflow item as disagree on allocated budget, ...) and one user needs to contact another. Names of users should be clickable, so that one can easily access contact information if the person needs to be contacted (notably organisation and email address).
- The history on project and subproject level can then focus exclusively on changes on project and subproject level respectively. Not showing all changes on all levels (project, subproject, workflowitem) will increase legibility of the history.

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 17:28

changed title from **Improve workflow item details and workflow item buttons, especially document validation** to **Improve workflow item details and workflow item buttons, especially document validation{+, as well as the history function+}**

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 17:28

changed the description

**Comment by mathiashoeld** [comment]
TODO: separate issues

**Comment by mathiashoeld** [comment]
Issue closed in favour of #233, #234, #235, #236
