### ISSUE TITLE
Search query not applied in table view when navigating back

### ISSUE THREAD

**Issue by schoel-bis** [openkfw/TruBudget#1235]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

When in table/list view on the projects level with a filter applied, navigating into one of the projects via the zoom icon and then going back via the browser's back button, the search query does not get applied and instead all projects are displayed.

This issue is not present in card view (search query is applied after using back).

Also, navigating directly to the filtered view via URL after first setting the project view to the table layout _will_ apply the filter (i.e. the issue does not show in this case).

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.0.1  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by daniel-arnauer** [comment]
The behavior of the table view is the intended behavior. The behavior at card view looks like a bug to me: after pressing back from a project, the searchterm in overview is deleted but it is still showing the filtered projects instead of all projects.
