### ISSUE TITLE
Make permission attribution more user friendly and automate when possible

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#125]
In GitLab by @lennart.ploen on Mar 12, 2019, 18:03

**Objective**: Automate attribution of some permissions and make interface more user friendly

**Purpose**: Defining user permissions has become easier with groups, but remains a cumbersome process: the user has to attribute the same rights on every level (project, subproject, workflow item), and some basic functionalities can be improved.

**Concept**: To facilitate the life of the user:
1. Automate permission attribution
- (a) Attribution of writing permissions automatically gives viewing permissions
- (b) Attribution of an assignee to a workflow item automatically attributes viewing permissions, permissions for closure of this workflow item, and permission to validate the document (if applicable, see issue 390) for the assignee
- (c) Attribution of any type of permission on Level N (e.g. Workflow item) automatically gives viewing permissions for the relevant items on level N-1 (e.g. sub-project), without having viewing permissions for the non-relevant items on level N-1. Otherwise someone with permissions for Level N will not be able to access level N (except if manually granted access on all N-1, N-2, …). Example: mtutelle gets viewing permission for a workflow item. He automatically gets viewing permissions for the relevant subproject (but not the other subprojects). As he gets viewing permissions for a subproject, he automatically gets viewing permissions for the relevant project.
2. In windows “set permissions for project/ subproject/ workflowitem”  
- (a) add “cancel” button to cancel modifications if error done
- (b) rename “close” button “submit”
- (c) attribute the permission at the moment of closure (“submit”) of the window (and not the moment you click on the name)
- (d) In the list of users, allow to sort the list: i) in alphabetical order (by last name), ii) by date of addition (“recently added”)

**Comment by mathiashoeld** [comment]
TODO: separate issues

**Comment by mathiashoeld** [comment]
Ad 1)a): will be done in #250
Ad 1)b): will be done in #251
Ad 1)c): This will not be done, since this is not desirable. Not all information on "above" levels should be accessible for all users automatically, so this permission should be grated with care.
Ad 2): will be done in #245
