### ISSUE TITLE
Back to top when scrolling on the main page

### ISSUE THREAD

**Issue by Malick-Niang** [openkfw/TruBudget#1260]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡
Freeze the SIGFE menu or insert a "back to top" button
Discussion-reference: <Insert discussion reference here>

**Comment by mayank2002-jpg** [comment]
Heyy! Can I work on this feature?

**Comment by daniel-arnauer** [comment]
This already exists in our frontend ([ScrollTop.js](https://github.com/openkfw/TruBudget/blob/main/frontend/src/pages/Common/ScrollTop.js)). If you want changes in the SIGFE frontend, you have to ask the SIGFE dev team
