### ISSUE TITLE
Create missing docker-compose files

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1263]
## Description 💡

Currently following docker-compose scripts are missing:

- [x] e2e-test
- [x] logging-service
- [ ] mutli-node

These should be added to make the docker-compose section complete.

**Comment by egdmrsy** [comment]
3 Topics regarding multi-node setup:

### Main Services
Which main services will be running by default? I assume we would have the following services boot up with multi-node:

- Alpha Node
- Alpha Api
- Alpha Frontend
- Beta Node
- Beta Api
- Beta Frontend

### Additional Services
Will additional/optional services only be started for alpha bc, api and frontend? Or will there also be additional services for the beta services possible?

**Build variations**
For every service we have multiple compose options such as a docker image from repo, local builds, hot-reloading, persistence etc.
Will alpha and beta separated with such variations?
**Example**: 
Take api as an example. Do we want to allow alpha-api to start as a local build and beta-api as a docker image from repository? or whatever we choose for alpha-api, also applies to beta-api? (meaning if we choose local build for alpha-api, beta-api will also use local build.)

**Comment by georgimld** [comment]
**Regarding the components to include in the multi-node setup:**
I woul add blockchain + api + frontend + provisioning for both alpha & beta, no additional services.

**Regarding build variations:**
I think the main focus of the multi-node docker-compose should be using fixed images (pulled from dockerhub). Having another docker-compose with local build is also useful, however having hot-reloading and persistance enabled doesn't seem necessary.
