### ISSUE TITLE
Fix bug in alpha connection with certificate

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1302]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
The askAlphaForPermissions function in the blockchain has a bug. The [rejectUnauthorized](https://github.com/openkfw/TruBudget/blob/ad3c99a7f2f63f09e98428de8c08f50489ca8ed4/blockchain/src/connectToChain.js#L145) option should be set to 'true' in production.

**Comment by Stezido** [comment]
the rejectUnAuthorized option is for disabling client verification (mutual ssl). So if mutual ssl should be used this is true but not necessarily in production.

**Comment by Stezido** [comment]
The code of the https Agent is mixing up tls.connect options as you can see [here](https://node.readthedocs.io/en/latest/api/tls/#tlsconnectoptions-callback), the `key` and `cert` options are relevant for client cert auth and the `ca` option is relevant for self-signed certificates.
The https agent of the blockchain is looking like this: https://github.com/openkfw/TruBudget/blob/ad3c99a7f2f63f09e98428de8c08f50489ca8ed4/blockchain/src/connectToChain.js#L139-L151
TruBudget blockchain should support following options for the initial register node request:
- En/Disable https
- En/Disable verification of server certificate (rejectUnauthorized)
- En/Disable mTLS (provide options `cert` & `key`)
- En/Disable self signed server certificates (provide optiond `ca`)

I would suggest to provide a possibility to pass all https agent options via one env var or file to be as flexible as possible.
