### ISSUE TITLE
Check TB based on security best practices

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1337]
## Description 💡

Check all TruBudget services based on the following best practices:
frontend, api, blockchain, email-service, excel-export service, storage-service

- [x] **Use secure coding practices**: Make sure to follow secure coding practices, such as input validation, output encoding, and error handling.
- [x] #1417
- [x] #1421
- [x] **Implement authentication and authorization:** Implement authentication and authorization to control access to sensitive resources. Use a well-established authentication protocol such as OAuth2 or OpenID Connect.
- [x] #1418
- [x] **Use secure third-party libraries:** Use secure third-party libraries, and keep them up-to-date with the latest security patches.
   - [x] our CI pipeline checks security vulnervabilites in libraries we are using (with npm audits)
- [x] **Use environment variables:** Use environment variables to store sensitive configuration information, such as database credentials and API keys. Do not hard-code sensitive information in your code.
    - [x] all services in TB use environment variables for storing (sensitive) configuration information
- [x] **Log security events**: Log security events such as failed login attempts and unauthorized access attempts. This can help you detect and respond to security threats.
- [x] #1424
- [x] **Regularly review and test:** Regularly review and test your code for security vulnerabilities. Use automated security testing tools to help identify vulnerabilities.
- [x] **Follow the principle of least privilege:** which means giving users and services only the minimum access necessary to perform their tasks. This can help minimize the impact of a security breach.

Document findings below and if applicable generate subtasks

**Comment by SamuelPull** [comment]
JWTs issueb by TB are stored in the one place they should not be: Local storage

**Comment by mayrmartin** [comment]
Closed since all applicable points are implemented or have a dedicated issue & will be scoped individually.
