### ISSUE TITLE
ui: format currencies and numbers according to the selected language or locale

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#135]
In GitLab by @kevinbader on Mar 15, 2019, 14:14

- Spacing
- Currency always before or always after

<img width="307" alt="image" src="https://user-images.githubusercontent.com/20185479/54906222-1f3aca00-4ee3-11e9-85c4-3c1d79bd13d2.png">

**Comment by gonzochic** [comment]
Currently we are only using fixed number formatting and fixed currency formatting. We should add something like a `locale` file where we can distinguish how to format.

https://github.com/openkfw/TruBudget/blob/e835c5ca8a19d2590fb32841b89e491d21cf1579/frontend/src/helper.js#L19-L23

https://github.com/openkfw/TruBudget/blob/e835c5ca8a19d2590fb32841b89e491d21cf1579/frontend/src/currency.js#L4-L10

**Comment by Stezido** [comment]
Fixed in #421
