### ISSUE TITLE
Provisioning Dataset with more exciting Demo data

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1365]
Proposition to extend the provisioning script by something more colorful:

- Amazon fund is ok
- Multiple Donors I -> Another image, "Joint Energy Transition Portfolio"
- Multiple Donors II -> Another image, "Education Program"

Any other ideas?

**Comment by SamuelPull** [comment]
Easy way to load data for provisioning: https://github.com/openkfw/TruBudget/pull/1379

**Comment by jzakotnik** [comment]
Piet created some good demo data, I'll try to transform it to json

**Comment by jzakotnik** [comment]
@georgimld @SamuelPull I have the sample data in a sandbox - is it possible to somehow export it into a json or should I write it from the sandbox manually into a json?

**Comment by jzakotnik** [comment]
Added demo data for timbuktu project and relevant users
