### ISSUE TITLE
Bug : Batch edit should show existing permissions but does not (see screenshot)

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#139]
In GitLab by @lennart.ploen on Mar 18, 2019, 12:26

![batchedit](https://user-images.githubusercontent.com/20185479/54906097-d8e56b00-4ee2-11e9-96dc-fba954485572.JPG)

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 18, 2019, 13:35

is this really a bug? 
let's assume we have 3 workflowitems with the followoing permissions for "Assign Workflowitem": 
* Workflowitem A --> testuser1
* Workflowitem B --> testuser2
* Workflowitem C --> testuser3

if i select all 3 of them, which users should be displayed in the "Assign Workflowitem" permissions field? if all 3 names are displayed, that would suggest that all 3 users have the given permission for all 3 workflowitems, which is not the case and is even more misleading. 

for this purpose, the next screen with the overview of impending actions was introduced where the user can see which actions will be performed.

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 18, 2019, 13:48

Agree with you that if workflow items A,B,C have different sets of permissions, nothing should be displayed. But if A,B,C have the same sets of permissions, why not show what they are? It saves the user 1 click for each line of permissions for every workflow item selected (14 clicks in the simplified example above), if he knows that for ex. Freya Negenborn already has sufficent rights for all the selected workflowitems in the above.

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 18, 2019, 19:35

On top of that, the batch edit is currently an overwriting function, which means I have to reselect all the users of batched items. Example, imagine as-is situation :

* Workflowitem A --> testuser1, testuser2, testuser3

* Workflowitem B --> testuser1, testuser2, testuser3

* Workflowitem C --> testuser1, testuser2, testuser3

Now, if I want to add testuser4 to all of items A,B,C, I have to select testuser4 AND reselect testuser1, testuser2, testuser3 for each item and each line of permission...very time intensive

**Comment by mathiashoeld** [comment]
IMHO this is not really a bug and is in accordance to how TruBudget was built. Every permission should be granted and revoked explicitly and with care. This also explains the decision to overwrite existing permissions - the permissions you see on the screen will be the permissions that are applied to the workflowitem after successful editing. 
For the case of the 3 users that are assigned to 3 workflowitems: This can be easily handled with groups - create a group with the 3 users, assign the workflowitem to the group and then add one person to said group. 
Therefore we will not implement this additional logic for now and I'll close the issue now. Feel free to re-open if you have additional information.
