### ISSUE TITLE
Add Opentelemtry Endpoints 

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1391]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Add two opentelemtry Endpoints in each TruBudget component for:
- [ ] status (inkl ping & duration of response)
- [ ] health (readiness)

- [ ] Azure integration

**Comment by SamuelPull** [comment]
We might just forego opentelemetry  and instrument TB with Application Insights? 

![Screenshot 2023-08-17 at 15 35 47](https://github.com/openkfw/TruBudget/assets/26326794/e62f9039-0b4d-4da7-8ca1-1c04b07b8c61)


Correlate the events, clicks and navigation with authenticated usernames, remove automatic periodic requests from tracking (notifications, list projects etc.)
