### ISSUE TITLE
Fix failing GitHub Action for publishing docs

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1398]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
Fix [failing GitHub action](https://github.com/openkfw/TruBudget/actions/runs/5266647636/jobs/9520843080#step:6:13), that fails during `Run echo "Generating api documentation" && cd api && npm ci --no-audit && npm run build-docs`, probably during the `npm ci --no-audit`command. This action is triggered only during release, but there should be a way to test it locally.

**Comment by SamuelPull** [comment]
Github action tested locally with https://github.com/nektos/act .
Bumping `node-version:` from  "12.x" to "16.x" fixed the error.
