### ISSUE TITLE
Management of corrections

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1399]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Management of Corrections💡

I would like to propose a feature to improve management of corrections, which would allow to mark workflow items that need to be corrected, and then through a toggle button in the UI, display or hide the corrected steps. The end user would then have the possibility to see the final or "clean" process, or has the view of all detailed steps including those that were corrected. 

The implementation could be as follows
1. Introduce a label "correction" (or similar) that can be applied to a workflow item
2. Add a toggle button in the frontend to display or hide corrections
3. Add a specific permission to "mark as correction" that can be given to the users - this would add a level of control to the feature.

**Comment by SamuelPull** [comment]
List of required changes:

* [ ] correction API endpoint (`/api/workflowitem.correct`)
* [ ] correction permissions
* [ ] upadte provisioning data with correction permissions to select users...
* [ ] update E2E

**Comment by SamuelPull** [comment]
For now, simple solution of enabling input of negative values (#1407) in workflow is implemented.

**Comment by georgimld** [comment]
Closed by #1407
