### ISSUE TITLE
Update Login page to allow authentication with AuthBuddy

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1449]
- [x] The feature is a child of #1432 
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Please see the parent issue. 

Use case is like this: I as a user want to login with my Orga credentials (samu@orga.de). My role is a Portfolio Manager, for which there exists in TB  a user with username Orga_PortofolioMngr. By clicking on the new login button, OAuth flow will be initiated.

<img width="729" alt="Screenshot 2023-09-08 at 08 25 12" src="https://github.com/openkfw/TruBudget/assets/26326794/06a6ff1a-030d-432d-8941-03e5c947d77d">

**Comment by georgimld** [comment]
Closed by #1468
