### ISSUE TITLE
100% CPU load in list view

### ISSUE THREAD

**Issue by schoel-bis** [openkfw/TruBudget#1472]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

When displaying projects in list view, one CPU core will be used 100%, even when the page is actually idle, i.e. no user interaction of any sort ever happens. This does not happen in card view.

### How to reproduce 🕹

Navigate to project list, switch to list view.

## Your Environment 🌎

Happens on all browsers.

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.1.1  |
| API             | v2.1.1  |
| Blockchain      | v2.1.1  |
| Export-Service  | v2.1.1  |
| Email-Service   | v2.1.1  |
| Storage-Service | v2.1.1  |

**Comment by SamuelPull** [comment]
Hey @schoel-bis , thanks for reporting the issue. There had been an infinite render bug which I fixed in https://github.com/openkfw/TruBudget/pull/1439 . Fix will be released in 2.3 version.
