### ISSUE TITLE
Be able to delete an uploaded document of an open (not closed) workflow item

### ISSUE THREAD

**Issue by lennartploen** [openkfw/TruBudget#1488]
...in order to avoid validating a workflow item with a wrong document attached.

**Comment by SamuelPull** [comment]
- [ ] Document delete domain action, service, http handler
- [ ] UI modification
- [ ] Document deleted event
- [ ] Only allow deletion of document from open workflow items
- [ ] E2E test: delete document from open wfi
- [ ] E2E test: cannot delete document from closed wfi
