### ISSUE TITLE
Error message whe uploading a document

### ISSUE THREAD

**Issue by LukasKM** [openkfw/TruBudget#1498]
- [ x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
When trying to upload a document, error message pops up saying: workflowitem.update failed: failed to get organizations: failed to get user: not found user xxxxxxxx. 

### How to reproduce 🕹
Assign a group to the workflow item. 
upload a document to the WF item. 

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.2.1  |
| API             | v2.2.1  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v2.2.1  |

**Comment by SamuelPull** [comment]
trubudget-operation-alpha-api-1             | {"level":50,"time":1698410329337,"hostname":"bc63d7d71a73","name":"Trubudget-Api","reqId":"req-10a","err":{"type":"VError","message":"workflowitem.update failed: failed to get organizations: failed to get user: Not found: user reviewers","stack":"VError: workflowitem.update failed: failed to get organizations: failed to get user: Not found: user reviewers\n    at /home/node/dist/workflowitem_update.js:148:27\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","jse_shortmsg":"workflowitem.update failed","jse_cause":{"type":"VError","message":"failed to get organizations: failed to get user: Not found: user reviewers","stack":"VError: failed to get organizations: failed to get user: Not found: user reviewers\n    at Object.updateWorkflowitem (/home/node/dist/service/workflowitem_update.js:99:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","jse_shortmsg":"failed to get organizations","jse_cause":{"type":"VError","message":"failed to get user: Not found: user reviewers","stack":"VError: failed to get user: Not found: user reviewers\n    at getOrganizations (/home/node/dist/service/workflowitem_update.js:122:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.updateWorkflowitem (/home/node/dist/service/workflowitem_update.js:97:39)","jse_shortmsg":"failed to get user","jse_cause":{"type":"NotFound","message":"Not found: user reviewers","stack":"NotFound: Not found: user reviewers\n    at Object.getUser (/home/node/dist/service/domain/organization/user_query.js:28:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getOrganizations (/home/node/dist/service/workflowitem_update.js:120:26)\n    at async Object.updateWorkflowitem (/home/node/dist/service/workflowitem_update.js:97:39)","ctx":{"requestId":"req-10a","source":"http"},"entityType":"user","entityId":"reviewers","name":"NotFound"},"jse_info":{},"name":"VError"},"jse_info":{},"name":"VError"},"jse_info":{},"name":"VError"},"message":"Error while updating workflowitem"}
