### ISSUE TITLE
Provisioning of custom users/roles including global rights

### ISSUE THREAD

**Issue by ZuitAMB** [openkfw/TruBudget#1499]
- [ ] The feature was discussed internally in a TruBudget deployment project.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

TruBudget's provisioning can be used to automatically generate TruBudget data, including users, groups and projects.
At the moment, the assignment of global permissions to users is hardcoded in [users_and_groups.js](https://github.com/openkfw/TruBudget/blob/main/provisioning/src/users_and_groups.js). 

A dynamic assignment of permissions defined in [users.json](https://github.com/openkfw/TruBudget/blob/main/provisioning/src/data/test/users.json) would allow us to create custom users with a custom selection of permissions. (For example, users with reading permissions only, another user with technical/blockchain permissions and a third one with project creation rights)

A possible user.json entry could look like:
```
{
    "id": "CustomProjectReader",
    "displayName": "Project Reader A",
    "password": "test",
    "permissions": ["project.list", "project.viewDetails"]
  }

```
As a developer, I would like to automatically provision TruBudget (functional) users including specific global permissions.

**Comment by egdmrsy** [comment]
Slight issue with the example user.json entry: project.list and project.viewDetails are not global permissions. Those permissions are given to the users per project basis and stored under projects. Same goes for subprojects and workflows.

**Comment by ZuitAMB** [comment]
Alright, so only global rights:
```
{
    "id": "CustomProjectCreator",
    "displayName": "Project Creator A",
    "password": "test",
    "permissions": ["global.createProject", "network.list"]
  }
```

**Comment by egdmrsy** [comment]
Feature PR is ready for review. Additional note: For users who should have all permissions, to avoid longer json file, it is enough to just add "all" to the permissions array. Provisioning service will ignore any other permissions in the array and will automatically grant all available permissions in this case. Example:

All permissions granted to the user adminA
`{
    "id": "adminA",
    "displayName": "Admin A",
    "password": "test",
    "permissions": ["all"]
  }

All permissions granted to the user adminB, other permissions in the array are ignored.
`{
    "id": "adminB",
    "displayName": "Admin B",
    "password": "test",
    "permissions": ["global.createProject", "all"]
  }
`
