### ISSUE TITLE
e2e-Tests only successful when test data is provisioned

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#151]
**Current:** When provisioning the prod data (by setting ENVIRONMENT_TYPE=PROD), the e2e tests fail with the message
```
CypressError: Timed out retrying: expected '<div.noFocus>' to be 'visible'

This element '<div.noFocus>' is not visible because it has CSS property: 'position: fixed' and its being covered by another element:

undefined
```

**Cause:** The list of users is too long which leads to part of the selection window not being displayed. Cypress interprets this as the element not being visible.

**Comment by jzakotnik** [comment]
Is this still needed? @mayrmartin I understand they work at the moment, should we close this?

**Comment by mayrmartin** [comment]
Yes, can be closed.
