### ISSUE TITLE
Filter function TruSupply/ TruBudget in TruBudget front end

### ISSUE THREAD

**Issue by lennartploen** [openkfw/TruBudget#1510]
If a partner country runs TruBudget, Trusupply and TruX on the same blockchain, then this data will also appear in KfW's node's front end.  How to distinguish supply chain data from budget data in the Front end? Possible to integrate simple filter function in front end from TruSupply in Brazil (under development) via pull request

**Comment by jzakotnik** [comment]
One idea could be to use tags and somehow introduce a simple filter on the frontend. 
The other idea could be to model this with respective access rights, if a project is a "supply chain project" and I have no rights to see others, I might also not see other data in the frontend.
