### ISSUE TITLE
Closed workflow items are sorted randomly

### ISSUE THREAD

**Issue by schoel-bis** [openkfw/TruBudget#1557]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Closed Workflow items are sorted in random order. The items 1, 2, and 3 in the screen below were originally ordered as 1, 3, 2 and also closed in this order. The timestamps on the `worflowitem_closed` events are `2023-12-06T11:58:24.925Z` and `2023-12-06T11:57:41.375Z` respectively for items 2 and 3, i.e. the timestamps actually say that item 3 was closed before item 2.

![Bildschirmfoto vom 2023-12-06 13-25-17](https://github.com/openkfw/TruBudget/assets/11717833/fcba4e58-5f92-4582-9b34-697ee7270d25)

### How to reproduce 🕹

Set up a workflow and close items. Observe random ordering.

## Your Environment 🌎

All 2.5

**Comment by SamuelPull** [comment]
AssertionError `Expected close event for workflowitem` isn't logged anywhere. Point of failure is function `closedAt` in src/domain/workflow/workflowitem_ordering.
