### ISSUE TITLE
Granting a permission to a project should be applied to all future subprojects & workflowitems

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1558]
### Discussed in https://github.com/openkfw/TruBudget/discussions/1541

<div type='discussions-op-text'>

<sup>Originally posted by **georgimld** November 23, 2023</sup>
One idea we had was to implement an option that allows users to grant a permission to a project that should be applied to all future subprojects and workflowitems. Currently, when granting a permission to a project, additional actions are created that grant permissions to subprojects and workflowitems as well, however only to existing ones. Future subprojects and workflowitem do not have the specific permissions. 

- one idea would be to mark this granting of permissions with a flag that would suggest the permission should be granted for all future resources that will be created in this project (for a specific user)

Please feel free to discuss the above mentioned idea or come up with additional solutions.
</div>

**Comment by SamuelPull** [comment]
<img width="942" alt="Screenshot 2024-01-11 at 16 04 30" src="https://github.com/openkfw/TruBudget/assets/26326794/db5cd2e8-613a-46c4-82fc-2858eb2c697c">

I'm thinking subproject can inherit project permissions and workflowitem subproject's.
