### ISSUE TITLE
Review e2e-test cases

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1560]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

- [ ] Review the logic of the e2e-test cases in TruBudget
- [ ] Check if there are any unnecessary checks or tests cases

**Comment by flavioludi** [comment]
Hi @georgimld, could you please assign this issue to me? Is there any place where I can find more information about what motivated this issue creation?

**Comment by georgimld** [comment]
> Hi @georgimld, could you please assign this issue to me? Is there any place where I can find more information about what motivated this issue creation?

Hi @flavioludi sorry for the late reply. I assigned you to the issue. I can give you a short overview about the motivation behind this issue. We have in TruBudget a large amount of e2e-tests, and they take a lot of time. So we want to take the time and check the logic of the e2e-tests, if there are any unnecessary or overcomplicated tests, duplicate tests or checks, or even things that are not tested propperly. Please reach out in case of any additional questions

**Comment by egdmrsy** [comment]
Hello @flavioludi, is it possible to provide short feedback on your work so far on the issue? :) We are not seeing any branches for this issue, and we were thinking to reassign it internally if you aren't working on it. Are you still planning to work on it?

**Comment by flavioludi** [comment]
Hi @egdmrsy! I didn't make a progress on that. I installed and ran the system, but I struggled with running the tests locally. So feel free to reassign it.

**Comment by egdmrsy** [comment]
Hi @flavioludi ! Thanks for the information! Could you please maybe provide feedback on why and what kind of difficulties were there while running the tests? After the setup, did you test the product manually? (e.g browsing on frontend, creating projects etc.) What kind of issues have you encountered during the local execution of the tests?

I am trying to assess some points for future improvements of the developer/operations experience. :)
