### ISSUE TITLE
Make Input fields for usernames wider

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1564]
Many user dropdowns are very short and therefore it is difficult to figure out, which user it is. Workaround via mouseOver works, but is very inefficient.
![image](https://github.com/openkfw/TruBudget/assets/551599/6fd34fe5-ff79-404e-a6b9-eec42635f273)

**Comment by SamuelPull** [comment]
- [ ] Project assignee
- [ ] Subproject assignee
- [ ] Workflowitem assignee
...
