### ISSUE TITLE
ui: Add functionality of filtering projects/subprojects/workflowitems by "tags"

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#157]
A user will be able to add **tags** to the **AdditionalData**-field of a project/subproject/workflowitem(resource). 
Afterwards she can filter by these tags to show specific resources only.

**Comment by lennartploen** [comment]
Also see issue 95 : https://github.com/openkfw/TruBudget/issues/95

**Comment by mathiashoeld** [comment]
tags were added in #342 and a simple search feature was implemented with #348. closing this issue
