### ISSUE TITLE
UI: Toggling vertical scrollbar causes background to resize

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1617]
when toggling between table view and card view, and when items (projects, subprojects, worfklowitems) are filtered by search, scrollbar may appear/disappear which causes the background to resize. looks almost like the screen is flashing.

**Comment by pmolnar-dev** [comment]
After analysis, this seems to be an expected behaviour in the browser. It could be cosmetically fixed by adding overflow-y: "scroll" into body css, but then we would have vertical scrollbar in the app at all times. Therefore I am closing this issue for time being.
