### ISSUE TITLE
Live refresh causes significant traffic and frequent “offline” message

### ISSUE THREAD

**Issue by schoel-bis** [openkfw/TruBudget#1630]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

In the case of our project in Tunisia, project list data is ~360kB in size. Live update reloads that entire amount every 5 seconds. This has two negative consequences:

* It causes ~4MB of extra traffic for each open UI per minute
* On slow connections, it often causes timeouts or other connection failures which will in turn cause an “offline” notice to pop up in the lower left corner of the screen, although the application is not actually off-line, only the connection could no't sustain the strain.

A few ideas for possible fixes/mitigations:

* Add a compression middleware to reduce the amount of data that goes over the wire
* Reduce the amount of data transferred for these updates (not sure if that is really possible, though)
* Change the logic such that only new and updated projects are transmitted, e.g. by including a cut-off timestamp in the request
* While at that: use WebSockets or at least long polling instead of simple polling to get those changes to the client

### How to reproduce 🕹

1. Add a significant number of projects
2. Navigate to project overview
3. Watch network monitor and, on a slow or throttled, or otherwise unreliable connection, observe the “offline” notifications popping up

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.?.?  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by galethil** [comment]
@schoel-bis could you please provide more details about how many projects do you have in Tunisia?

**Comment by schoel-bis** [comment]
That's 117 projects currently. The total size of the project list downloaded every 5 sec (before applying the new configuration from #1638) is 371.09 kB.

**Comment by SamuelPull** [comment]
@schoel-bis Thank you for bringing this to our attention, and for the ideas. Websockets are unfortunately of question, some partners can't use them. 
All users have now an option to turn off live update. 
<img width="356" alt="Screenshot 2024-03-26 at 08 37 11" src="https://github.com/openkfw/TruBudget/assets/26326794/c6a05f8b-c654-4ab1-935d-44d478f1b50f">

We're working on a new endpoints for projects and subprojects with pagination, hopefully for the 2.10.0 release.
