### ISSUE TITLE
Add additional interfaces for storage solutions

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#1656]
## Description 💡
At the moment the Storage Service can only connect and use MinIO as a storage backend. Other solutions which are based on the S3 protocol should be supported as well. Additionally, it should be possible to connect to other storage solutions with ease (i.e. Azure Blob Storage). MinIO provides a Gateway that can place files on different storage solutions using it would reduce the implementation/maintenance effort for us. Unfortunately, the gateway is deprecated but there are some alternatives (https://github.com/minio/minio/issues/14331)

**Comment by jzakotnik** [comment]
@mayrmartin to reduce complexity, maybe a direct integration to Azure Blob makes sense - a kind of intermediate broker for various data storage solutions adds overhead, or?

**Comment by mayrmartin** [comment]
@jzakotnik Yes exactly, we are currently working on a direct integration to AZ Bolob
