### ISSUE TITLE
More tooltips or help adornments for text inputs

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1698]
When using various text fields (e.g. to create a subproject), it would be useful to add tooltops or a small question mark for additional help what to fill into the field. Can this be configured somwhere?

For example:

- "Organisation" in subproject, what is meant with organisation? Is it the partner executing agency or the source of the budget, or something else?
- "Total budget", is this the planned budget (which changes if the plan changes) or the originally agreed budget or something else?

Check using of instructions tour

**Comment by pmolnar-dev** [comment]
@jzakotnik So I was looking at Material UI and we have help icon at our disposal. Also tooltip component is part of Material UI too so there is no problem there either. The only thing is that we need to create language strings for these tooltip messages. I doubt that we can make good ones from google translator, so my question is, do we have someone dedicated who can create these language strings and share them? The last question is regarding places where to add these messages. You mentioned Organisation and Total Budget. Are there any more?

**Comment by jzakotnik** [comment]
I think the help icon with a click is maybe more compatible to web + tablets + mobile. Can you create placeholders for the strings and then we edit the real strings in some config file?

**Comment by pmolnar-dev** [comment]
@jzakotnik I have made some progress on the tooltips. It can look something like this (icon is subject to change)
<img width="829" alt="Screenshot 2024-03-11 at 12 56 36" src="https://github.com/openkfw/TruBudget/assets/55734106/b831618d-40f5-44fd-9128-f7360c69ec7b">
We should be cautious of using these tooltips and helper icons though, because we can't add them everywhere in forms. It will just get messy for users. We should discuss this on some refinement session.

**Comment by jzakotnik** [comment]
Yeah, this looks pretty messy, if there are all these icons around. 

Potentially it could be part of the label but this is only visible once you focus the field?
![image](https://github.com/openkfw/TruBudget/assets/551599/ef9d150a-3ec8-49b4-b058-2c719fdfdd31)

**Comment by pmolnar-dev** [comment]
@jzakotnik The thing is that you can't have it in Dropdown label. Material UI just does not support it. Also it does not make sense to have it up there from UX perspective. Icon does not make sense level above when user is filling dropdown down below. The solution I made is the cleanest. It can also make sense to ask Serkan for some UX input and maybe rework the whole Dialog window so we don't have 3,4 input/dropdowns on same line it would be much cleaner.

**Comment by jzakotnik** [comment]
Yeah, makes sense. Only alternative in my mind is to save icons - have only one icon per row or so and then in the dialog we explain all 3 fields... is more text, but on the other side it's all 1 context to understand.. What do you think?

**Comment by jzakotnik** [comment]
Can you add placeholders (e.g. the same as label name), let us know which file contains the strings and then we create a PR with the respective strings filled out incl translations?

**Comment by pmolnar-dev** [comment]
@jzakotnik Yes sure I can do that

**Comment by pmolnar-dev** [comment]
@jzakotnik so I merged the issue and this is path to component that has new strings: frontend/src/Pages/Common/Budget.js
and I am also adding screenshot where to find new strings. I added them to every language file.
<img width="517" alt="Screenshot 2024-03-14 at 12 06 19" src="https://github.com/openkfw/TruBudget/assets/55734106/8f356dce-9f63-441f-8926-cca59b788c87">
