### ISSUE TITLE
Modify default assignee behaviour

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1720]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
Currently when selecting the "default asignee" option while createing a subproject, the workflowitm assignees can never be changed again. This is not made clear when creating the subproject.

There are 2 possible ways to fix this:

1. Add a tooltip of warning message during assignee creation to help the users understand the implications of this option (that a "default assignee" can not be changed later)
2. Allow the users to modify the assignee of workflowitems even after the "default assignee" was checked -> we need to challenge what the desired result is of the "default assignee" and check if it still makes sense

**Comment by pmolnar-dev** [comment]
@georgimld Just on top of my head we can consider this solution. What do you think?
<img width="852" alt="Screenshot 2024-03-14 at 10 29 46" src="https://github.com/openkfw/TruBudget/assets/55734106/b219168a-d4ff-49b5-956d-35049b019a69">

**Comment by pmolnar-dev** [comment]
@jzakotnik I would like to implement this solution into the Subproject form. I can again create PR for this and then message you here for translations as I did in previous issue about the tooltips in the same form. Is it okay?
<img width="845" alt="Screenshot 2024-03-15 at 09 17 48" src="https://github.com/openkfw/TruBudget/assets/55734106/00add297-afac-400f-a967-fde0bea74194">

**Comment by jzakotnik** [comment]
Sounds good!
