### ISSUE TITLE
Unordered workflow items

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1829]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository. 
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Workflow items in a subproject are by default ordered, and have to be processed in a strict sequence.

Perhaps subproject could have an option to create an unordered workflow items list?
Or individual workflow items could be unlinked?

Both approaches have their pros and cons. We should investigate which approach is better fit in TB.

Discussion-reference: https://github.com/openkfw/TruBudget/discussions/1821

**Comment by jzakotnik** [comment]
Since we removed the restricted/generic Workflows, that space could be re-used from the UX perspective to offer this feature.

I assume that the mode (flow/unsorted) doesn't need to be changed afterwards.

The drop down could be
**workflow** or **action list**
