### ISSUE TITLE
Long workflow item titles break layout

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1850]
In some cases the workflow titles are pretty long (e.g. copy pasted from respective workflow documents) - in this case it would be good to truncate the title at some good point and potentially leave it as tooltip.

**Comment by pmolnar-dev** [comment]
@jzakotnik shouldn't we also restrict length of workflow item title when user is creating one? I am not sure what are the requirements and if it is necessary to have workflow title as long as you described in the picture

**Comment by pmolnar-dev** [comment]
@jzakotnik ye I would go for massive trim there and put whole title to tooltip maybe because what I see in the picture is not good at all

**Comment by jzakotnik** [comment]
Yes I agree. Actually I am not skilled enough in frontend dev, but would trim be dynamic based on the viewport?

**Comment by pmolnar-dev** [comment]
Trim is based on the width of the field itself so if it the title field is perhaps 200px then it would not go more then that. In fact in this case it is percentage based that is why it is stretching vertically.

**Comment by pmolnar-dev** [comment]
@jzakotnik  I would suggest something like this, text wont go pass 2 lines of text so it won't break UI design and tooltip will be in place so user can see whole title if he wants.
<img width="934" alt="Screenshot 2024-05-31 at 10 46 56" src="https://github.com/openkfw/TruBudget/assets/55734106/ac2d1af6-b347-421b-a426-7305fe9ae557">

**Comment by jzakotnik** [comment]
@pmolnar-dev I think this looks good, thanks!
