### ISSUE TITLE
Layout bug for validation of documents

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1861]
The layout seems broken here:
![image](https://github.com/openkfw/TruBudget/assets/551599/e384ca25-ccae-4db7-9206-f74b45e2ecad)

**Comment by pmolnar-dev** [comment]
I would not say layout is broken :). It is just that content can't be displayed all at once that is why we have the scroll there

**Comment by jzakotnik** [comment]
@pmolnar-dev hehe, you're right, it's not broken, only looks broken ;)

**Comment by galethil** [comment]
@jzakotnik considering the upcoming new design, where it will be fixed, can we close the issue? Or do you suggest to implement it anyway? E.g. with extending size of pop up window?
