### ISSUE TITLE
Change wording of "default assignee" to "fixed assignee"

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1865]
![image](https://github.com/openkfw/TruBudget/assets/551599/3b01dea5-e1fb-4ccc-8685-0a7c0873ee3a)

**Comment by jzakotnik** [comment]
And maybe add a checkbox to enable this, so by default you don't click on this

**Comment by georgimld** [comment]
Lets wait for more imput before we start this issue

**Comment by AmelieAnnemie** [comment]
Please change the wording from "Default assignee" to "Fixed assignee". 

Consider change in all languages.
