### ISSUE TITLE
Rename the ‘Total Budget’ overview to ‘Participating Stakeholder’. 

### ISSUE THREAD

**Issue by AmelieAnnemie** [openkfw/TruBudget#1874]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Rename the ‘Total Budget’ overview to ‘Participating Stakeholder’. 

Please change in all languages.

**Comment by jzakotnik** [comment]
@SwarnenduG07 It could also be done via a translate (like google translate)

**Comment by SwarnenduG07** [comment]
> @SwarnenduG07 It could also be done via a translate (like google translate)

Ok then. I am working on it
