### ISSUE TITLE
Change of the Workflowitem designation

### ISSUE THREAD

**Issue by AmelieAnnemie** [openkfw/TruBudget#1886]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Replace the word "workflowitem" (and "workflow item") with "workflow action". 

See screenshot where adjustments need to be made. 

Please also adapt in all other languages. 

![Wording Workflowitem](https://github.com/openkfw/TruBudget/assets/172389195/f0a8d522-244f-4a5d-8e77-9f349b0df9b4)

**Comment by galethil** [comment]
Hi @AmelieAnnemie , workflow by it's definition describes a system or a mechanism to handle work (usually repetitive tasks). So in this case there are "items (lines) of this workflow". You are not creating a workflow itself, but it's part (item) visually represented as one row in the table.
So I would suggest that the correct phrase to use here is "workflow item", not just "workflow". Basically, just split the non-existing word into 2 words.
Do you agree?

**Comment by AmelieAnnemie** [comment]
Thank you for your response Peter. That sounds logical to me, lets do it like you said.

**Comment by jzakotnik** [comment]
@galethil Yes, from engineering/logical view, I also see it like this. For some reason "item" is confusing. There also doesn't seem to be a difference between "subproject" and "workflow" in this logic.
What about "workflow step" or "workflow activivity"? I think only "item" is confusing.

**Comment by galethil** [comment]
I agree @jzakotnik basically it would make also sense to call it "subproject item" , or "subproject step". Not sure, how to find the best name, though.
