### ISSUE TITLE
Create all initial letters uniformly small for workflow item 

### ISSUE THREAD

**Issue by AmelieAnnemie** [openkfw/TruBudget#1887]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

See screenshot, when creating a workflow item, "Not" is displayed with a capital letter at the beginning. Please change to "not" so that everything is standardised. 

![Small letters](https://github.com/openkfw/TruBudget/assets/172389195/b9c39337-2f35-4f97-b1ee-9544d229644f)

**Comment by jzakotnik** [comment]
Someone put an `api` label on this, but why?

**Comment by AmelieAnnemie** [comment]
> Someone put an `api` label on this, but why?

Hi Jure, fyi - the label was automatically applied by the bot. I will check this next time.
