### ISSUE TITLE
Some workflowitems cannot be closed due to error

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1894]
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Encountered a 5xx error when trying to close WF item in Amazonas Fund > Furniture > Payment Final Installment. 
"workflowitem.close failed: close workflowitem failed: Failed to apply workflowitem_closed: validation of workflowitem failed: failed to apply workflowitem_closed: "exchangeRate" is required."
Opening an issue to investigate whether this is due to an error in the data or application.

### How to reproduce 🕹

0. Start TB in dev mode with provisioned data
1. Login as jxavier
2. Open Amazonas Fund > Furniture
3. Start closing WF items
4. ...

### Screenshots 📷

<img width="1714" alt="Screenshot 2024-07-01 at 08 38 55" src="https://github.com/openkfw/TruBudget/assets/26326794/e25a94eb-07df-45c2-b9f7-54edb47a601f">

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

**Comment by jzakotnik** [comment]
I could repdroduce the error in the release branch as described
