### ISSUE TITLE
Add aditional comment field for uploaded documents

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1900]
When uploading a document, users put metadata in the filename because there is not comment field for the file name (e.g. draft or final or so). Would be great to have a text field there.

See also issue #1895

**Comment by SamuelPull** [comment]
- [ ] Add optional text field input and display it
- [ ] Improve file upload instructions
- [ ] Display file upload date and time
- [ ] Add progress spinner while file is uploading (it is possible to submit new workflow item while file is not uploaded yet, esp. larger sizes)
