### ISSUE TITLE
eMail notification when a document is added to a workflow assigned to me

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1903]
Could an email notification be triggered when a workflow assigned to me is changed, e.g. when a document is added?

**Comment by jzakotnik** [comment]
@galethil This would be good for the next milestone

**Comment by galethil** [comment]
@jzakotnik I checked the notifications flows. App is creating notification on workflow update to the user that is assigned. It is also sending email in this case. Is there any specific issue with it?

**Comment by jzakotnik** [comment]
Sorry, I might have misunderstood what was actually needed :) Let's close here and I check again.
