### ISSUE TITLE
Only one tag is shown in the workflow item overview even if more are present

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1906]
We added various tags to a workflow item, but only the first is rendered. Seems in the code only 1 tag is used?

```
<div className="tag-cell">
                  {tags.length > 0 && (
                    <Chip
                      label={tags[0]}
                      size="small"
                      onClick={(event) => {
                        props.storeWorkflowitemSearchTerm(`tag:${event.target.innerText}`);
                      }}
                      sx={{ backgroundColor: (theme) => theme.palette.tag.main, color: "white" }}
                    />
                  )}
                </div>
```

![image](https://github.com/openkfw/TruBudget/assets/551599/33e6b9fc-657d-47a4-a996-5ae59a5ee27a)

**Comment by SamuelPull** [comment]
This is mainly due to the table size. Perhaps add and inidicator that there are more tags and display them on mouse hover? (Wouldn't work with phones and tablets)

**Comment by jzakotnik** [comment]
But if there's space on a large screen, they could still be displayed

**Comment by jzakotnik** [comment]
Quick workaround: adding +x if there are more tags
