### ISSUE TITLE
Remove stale bot from the project

### ISSUE THREAD

**Issue by galethil** [openkfw/TruBudget#1917]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Remove the stale bot https://github.com/apps/stale from the project pipelines.

Discussion-reference: <Insert discussion reference here>

**Comment by SamuelPull** [comment]
Stalebot uninstalled
