### ISSUE TITLE
Copy Paste functionality seems to work only on page 1 of projects

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1944]
I tried to copy paste workflows from a project to the project number 16 in the demo installation, but it is not shown in the dropdown menu. Could it be that only page 1 is used for the copy-paste functionality?

If it cannot be reproduced, I can attach screenshots.

**Comment by galethil** [comment]
@jzakotnik can you please attach the screenshot, I'm not able to reproduce it.
