### ISSUE TITLE
Root user needed for some operations

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1970]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

In a couple of services, there's the check for a explicit root user, via `userId === "root"`. Is this correct? I would have expected that the root user is disabled and the services are used via respective authenticated users in their role.

**Comment by SamuelPull** [comment]
@jzakotnik If it is correct depends on a criterion I suppose. 
In the email service, root can create, read, update, and delete email addresses. On the other hand, frontend doesn't expose a way for root user to read or modify these. I think it reflects conflicting design decisions, and as you wrote, root access in the email service to user's addresses should be disabled.
Provisioning and migration are necessary.
Frontend uses the check to i.a. limit the actions root can do (root can't create projects).

**Comment by jzakotnik** [comment]
I agree, let's close this
