### ISSUE TITLE
Check for additional services during runtime and not only during login

### ISSUE THREAD

**Issue by galethil** [openkfw/TruBudget#1975]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Check for excel-export and email-service are performed only during the login.
It might happen that service is not available during login (redux CHECK_EXPORT_SERVICE_SUCCESS is never triggered), but available later on (or the opposite). 
This healthcheck should be performed at least on Status screen, where the status of services is displayed.

**Comment by SamuelPull** [comment]
At least on status screen by polling.
