### ISSUE TITLE
Update Postman collection

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#199]
Since there were some changes in the API, the Postman collection is outdated and needs to be updated. 

One extra nice bonus would be adding automatic authentication before each call.

**Comment by gonzochic** [comment]
This would be a really nice feature for onboarding new users and giving them some help when exploring the API (as an alternative to the Swagger Config).

**Comment by mathiashoeld** [comment]
Additionally: 

- [ ] Automatically authenticate before each request
- [ ] Add scripts to autmatically create a new project, subproject, workflow item, generate notification etc.
- [ ] Add file to create environments

**Comment by Stezido** [comment]
Additionally:

- [ ] check endpoints in API documentation
