### ISSUE TITLE
frontend: postcss-resolve-url: postcss.plugin was deprecated.

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#2017]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Migration guide:
`https://evilmartians.com/chronicles/postcss-8-plugin-migration`

### How to reproduce 🕹

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You will see error in console>
4. ...

### Screenshots 📷

Add screenshots or screen recording video if applicable.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

**Comment by MartinJurcoGlina** [comment]
not applicable as postcss is a subdependency of another package so we can't do the migration to another package. Postcss is in override in package.json to force newer version that doesn't have vulnerabilities.
