### ISSUE TITLE
Add location metadata to nodes

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#21]
In GitLab by @kevinbader on Jul 30, 2018, 09:30

Let's figure this out on the backend first, then add a follow-up task for including the location in the UI.

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Aug 23, 2018, 08:35

changed title from **api: Add location {-(meta data) to nodes response-}** to **api: Add location {+to nodes+}**

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Aug 23, 2018, 08:35

changed title from **{-api: Add location-} to nodes** to **{+Add location meta-data+} to nodes**

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Aug 23, 2018, 08:36

changed title from **Add location meta{---}data to nodes** to **Add location metadata to nodes**

**Comment by gonzochic** [comment]
We removed the node map therefore not needed anymore.
