### ISSUE TITLE
api: enforce decimal point format for numbers and migrate existing numbers to comply

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#216]
We allow commas instead of points in exchange rate field - this leads to NaN on api side

**Comment by kevinbader** [comment]
We've defined that the API would _never_ interpret amounts. It could be argued that it'd make sense to extend that to exchange rates. In that case I would expect the UI to prevent this. @gonzochic thoughts?

**Comment by kevinbader** [comment]
as per discussion:

1. for all `amount` and `exchangeRate` fields, enforce using a point as the decimal sign in the controller; that is, all new modifications must use a decimal point for any currency-related fields.
1. write and run a migration script that, using root permissions, traverses all projects, including subprojects and workflowitems; this script should look for decimal commas and replace any occurences with decimal points by producing update events.
1. use the following regular expression for amount and exchangeRate fields in the domain layer: `^([+-]\s?)?[0-9]+(\.[0-9]+)?$` (note that thousands separators are not allowed).
