### ISSUE TITLE
Clicking on the network icon (top right), I should see the "NodeMap" page

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#25]
In GitLab by @kevinbader on Aug 9, 2018, 14:53

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Aug 21, 2018, 10:23

changed title from **Clicking on the network icon (top right), I should see the "Node{-s-}" page** to **Clicking on the network icon (top right), I should see the "Node{+Map+}" page**

**Comment by phpai** [comment]
In GitLab by @Stezido on Nov 16, 2018, 12:49

@gonzochic do we still consider implementing the "NodeMap"

**Comment by gonzochic** [comment]
Nodemap was removed therefore closing issue.
