### ISSUE TITLE
api: Automatically give write permissions 

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#250]
### Description
When granting write permissions for a resource, the permissions to view the resource should be granted automatically. 

### Solution
The confirmation dialog shall be used to implement this feature. Before using the dialog it has to be refactored:
#### ConfirmationDialog Refactoring:

- [ ] Implement a grantPermission specific confirmation dialog 
- [ ] Get helper function getMissingViewPermissions into own folder

**Comment by Stezido** [comment]
Since we want the api to prevent executing user intents with unexpected behaviour like granting permissions when assigning users, we should handle this on UI-level. See [#23](https://github.com/openkfw/TruBudget/issues/23)

**Comment by mathiashoeld** [comment]
same idea as for #251
