### ISSUE TITLE
api: Automatically give permissions when user is assigned

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#251]
When a user is assigned to a workflow item, the permissions for viewing, closing, etc. should be granted automatically.

**Comment by Stezido** [comment]
Since we want the api to prevent executing user intents with unexpected behaviour like granting permissions when assigning users, we should handle this on UI-level. See [#23](https://github.com/openkfw/TruBudget/issues/23)

**Comment by mathiashoeld** [comment]
idea: the process should not be totally automatic, but rather there should be an option (e.g. checkbox) that enables permissions for the parent project/subproject
