### ISSUE TITLE
Translations ENG-> FRA and FRA->FRA corrections

### ISSUE THREAD

**Issue by lennartploen** [openkfw/TruBudget#262]
•	“currency” -> “monnaie” (and not “devise”, as also local currency can be selected, should be corrected everywhere)
•	"export" -> “exporter” (and not “exporté”, should be corrected in user menu)
•	"Organization" -> "Organisation" (should be corrected when adding a new project/subproject)
•	"Projected Budget" -> "Budget prévu" (and not "budget estimé", should be corrected everywhere)
•	« devise du projet" -> « Monnaie » (should be corrected when adding a new subproject)
•	"subproject currency" -> "Monnaie du sous-projet" (should be corrected on subproject level)
•	“Ratio budgétaire attribué” should be replaced by “Taux d’allocation budgétaire (alloué/prévu)"
•	“Ratio du budget décaissé” should be replaced by  “Taux de décaissement (décaissé/alloué)"
 
Note: the notion "sub project" is to be replaced everywhere in the UI by "component" (in French: sous-projet -> Composante)

**Comment by mathiashoeld** [comment]
@lennartploen 
* "monnaie" is neutral -> "le monnaie"? 
* could not find any "Organisation" that was written wrong - can you paste a screenshot of the page where it is not correct? 
* for projected budget: we have the following lines: 
-- "Taux d’estimation du budget(estimé/total)"
-- "Non estimé"
are these correct? 
* "devise du projet" - could not find it anywhere
* "Monnaie du sous-projet" - shouldn't this be "Monnaie de la composante"?
* Renaming of subproject was done in #218

**Comment by lennartploen** [comment]
@mathiashoeld 
- please take off "monnaie" and stick to "devise" (we had some French discussions and finally decided devise is better, appologies for the confusion)
- "Organization" & "devise du projet" see screenshot attached. Replace "devise du projet" by "devise"
- Budget estimé to be replaced by Budget prévu: also see screenshot attached
- "subproject currency" should be "Devise de la composante" (stick to devise but replace "sous-projet" by "coposante"
![Capture](https://user-images.githubusercontent.com/48890587/57438526-6b985a00-7244-11e9-8e36-e959619ee503.JPG)
![Capture2](https://user-images.githubusercontent.com/48890587/57438460-4572ba00-7244-11e9-86a2-7c1a87ce7fd3.JPG)

**Comment by mathiashoeld** [comment]
@lennartploen thanks for the input. 
please see #278 in the [files changed](https://github.com/openkfw/TruBudget/pull/278/files) section you can see and review the changes.
