### ISSUE TITLE
API: Exchange rate is not required when amountType is allocated/disbursed

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#265]
***ExchangeRate*** should be required when ...

amountType === allocated/disbursed 
AND 
workflowitem-currency !== subproject-currency

**How to test?**
Body-Request of ***subproject.createWorkflowitem:***

```json
{
	"apiVersion": "1.0",
	"data": {
		"projectId": "{{projectId}}",
		"subprojectId": "{{subprojectId}}",
		"displayName": "Testname",
		"amount": "1",
		"currency": "EUR",
		"amountType": "disbursed"
	}
}
```

Response should be:
```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body.data should have required property 'exchangeRate'"
}
```

**Comment by kevinbader** [comment]
@Stezido the validation is done once the workflowitem is being closed - as long as the workflowitem is _open_ you can do pretty much what you want with it. I'd suspect TruBudget to reject `workflowitem.close` on this workflow item. Can you confirm?

**Comment by Stezido** [comment]
@kevinbader thank you, I can confirm. It works as described.

On frontend side we should handle empty exchangerate-fields instead of showing undefined:

![image](https://user-images.githubusercontent.com/5485771/58077906-cd928100-7bad-11e9-93df-5909096c3885.png)

I created a new issue [#297](https://github.com/openkfw/TruBudget/issues/297) according the exchangerate-field on frontend and close this one.
