### ISSUE TITLE
On the Nodes page, I should be able to hide addresses I'm not going to approve - 8SP

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#27]
In GitLab by @kevinbader on Aug 9, 2018, 14:54

**Comment by phpai** [comment]
In GitLab by @kevinbader on Aug 24, 2018, 13:26

It would probably make sense to hide outdated addresses automatically and for all users:

- every time a not-yet-approved node is "seen", a "last seen" timestamp is updated
- not-yet-approved nodes with a "last seen" timestamp older than a week are no longer shown on the nodes page.
- When later they connect again, their timestamp is updated and they're displayed again.

**Comment by mathiashoeld** [comment]
relates to #189

**Comment by mathiashoeld** [comment]
relates to #190

**Comment by georgimld** [comment]
Proposed solution: 
When a user from an organization hides/declines a request, a new event is saved in the `nodes` stream, with the properites:

- type of event
- organisation of the user hiding the request
- address of the node to be hidden
- organization of the node to be hidden

When listing all nodes, the request will then be hidden for all nodes of that organization (maybe show them in a tab with all hidden requests)
