### ISSUE TITLE
api: Make user.intent.(grant/revoke/list)Permission global

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#328]
Currently the user permissions for granting, revoking and listing permissions are given for each user separately. 

Analogously to projects it would be a good idea to make this permission global to be able to easier manage these permissions for admin users.

**Comment by jzakotnik** [comment]
This is related to the [discusssion ](https://github.com/openkfw/TruBudget/discussions/1541), which will revamp the permission system. Therefore I would close it here.
