### ISSUE TITLE
For changes in a subproject's workflowitem ordering, the history doesn't show _what_ has changed

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#33]
In GitLab by @kevinbader on Aug 14, 2018, 11:25

From #47:

Currently the history item when the order of the workflowitems change looks like: 
```text
mstein changed the workflowitem ordering 
```

It would be nice to get details about what exactly changed.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Aug 14, 2018, 11:25

changed the description

**Comment by mathiashoeld** [comment]
relates to #236
