### ISSUE TITLE
e2e: automatically run e2e tests for outside contributions

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#338]
Continued from #319

# Situation

The job responsible for pushing docker images uses secure environment variables (credentials to docker repo). These env variables are not available for PRs sent from forks, due to [travis security restriction](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).

# Possible Solution

- tbd

**Comment by Stezido** [comment]
e2e-tests are started for each PR. It doesn't matter if the PR is created from a fork or not. Since we are not using travis anymore this issue is deprecated. (Using github actions)
