### ISSUE TITLE
Add missing unit tests

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#35]
In GitLab by @Stezido on Sep 25, 2018, 10:26

There exist only a few unit tests.
Every endpoint should have at least one unit test showing that the endpoint is working properly.

We should have meaningful tests and I would propose to have a test coverage somewhere around 80%.

**Comment by phpai** [comment]
In GitLab by @Stezido on Nov 16, 2018, 12:25

changed title from **Add missing {-integration-} tests** to **Add missing {+unit+} tests**

**Comment by phpai** [comment]
In GitLab by @Stezido on Nov 16, 2018, 12:25

changed the description

**Comment by phpai** [comment]
In GitLab by @Stezido on Nov 16, 2018, 12:26

changed the description

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Nov 19, 2018, 17:16

changed the description

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Jan 8, 2019, 15:46

@Stezido can we add a more detailed discussion on what we exactly want to test?

**Comment by phpai** [comment]
In GitLab by @Stezido on Jan 10, 2019, 10:24

assigned to @phpai

**Comment by phpai** [comment]
In GitLab by @phpai on Jan 24, 2019, 15:46

assigned to @Stezido and unassigned @phpai

**Comment by phpai** [comment]
In GitLab by @phpai on Jan 24, 2019, 15:47

I added unit tests for blockchain for the module "kubernetesClient".
Additional unit tests are being created during refactoring

**Comment by phpai** [comment]
In GitLab by @Stezido on Jan 24, 2019, 15:49

While refactoring the Trubudget-code we implement unit tests for each endpoint of Trubudget. After refactoring is completed we check the coverage again.

**Comment by phpai** [comment]
In GitLab by @Stezido on Mar 14, 2019, 17:11

unassigned @Stezido

**Comment by phpai** [comment]
In GitLab by @Stezido on Mar 22, 2019, 13:29

The issue has to be more specific about unit tests. With a list of missing unit tests we could track our progression. The unit tests for the refactored endpoints will be fully implemented with %"TruBudget 1.0.0\-beta.7"

**Comment by mathiashoeld** [comment]
add unit tests whenever a bug is fixed or a feature is added
