### ISSUE TITLE
Not possible to add fields to resources and being backwards compatible

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#360]
## Issue
The validation of Trubudget (Joi) does not allow additional fields and would respond with an validation error. Currently the api ignores the whole resource if an unknown field is found. This leads to not showing whole projects if they have an additional field of a new trubudget version. 

_Originally posted by @mathiashoeld in https://github.com/openkfw/TruBudget/pull/344#issuecomment-507724002_
Compatibility issue: When projects with tags are created in the new version, it is not available in earlier versions that do not have this issue (<1.3.0).
## Solution
Joi has an option to strip all additional unknown fields (stripUnknown).

Following table shows what would happen if a read or write intent is done with new fields and the stripUnknown option:

|   Intent   | Old Api version  | New Api version|
| ---------- | --------------------- | ------------- |
|     Read    | ignores new fields  | responds with new fields |
|     Write    | rejects request        | uses new fields  |

## Consequences
The disadvantage of stripping unknown fields is that there only will be an error if a required field is missing. So if a non required field is misspelled, the field is silently stripped. Note that api requests with misspelled fields are rejected by the fastify swagger schema and the user gets informed. The issue persists only internally, developer have to keep that in mind.   

## Affected Resources
Following resources could/should be expandable with additional fields:

- [ ] project
- [ ] subproject
- [ ] workflowitem
- [ ] user (user record)
- [ ] group
- [ ] notification
- [ ] global permissions

**Comment by Stezido** [comment]
@gonzochic @kevinbader @mathiashoeld , what are your thoughts?

**Comment by kevinbader** [comment]
agree - in order to support future versions, the validation _must_ ignore any additional fields. Unfortunately, I've never made sure the validation behaved as I thought it would - turns out it doesn't.

However, I'm not sure about that "Old API version rejects write request". For example, I don't see why creating a project in the old version shouldn't work. Any newer fields that might exist in future versions must be optional anyway - otherwise, the change wouldn't be backward compatible.

**Comment by Stezido** [comment]
@kevinbader thanks for your participation. 
The old api version rejects write requests **with new fields** . As you've written creating a project does work on older versions in old format.

I will create a PR fixing that issue. The fix should be available in [v1.3.0](https://github.com/openkfw/TruBudget/milestone/19)

**Comment by Stezido** [comment]
solved in #361
