### ISSUE TITLE
Validate and implement a tracing solution

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#37]
In GitLab by @saschak_94 on Oct 9, 2018, 17:26

Currently we validate [Jaeger Tracing](https://www.jaegertracing.io/)

Branch "jaeger-tracing"

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Oct 9, 2018, 17:27

changed the description

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Oct 9, 2018, 17:28

changed the description

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Oct 9, 2018, 17:29

mentioned in commit 5dc4ce479e50098c61c1ef820eaaffa5cc979b9d

**Comment by gonzochic** [comment]
At this time, we decided to descope the use of Jaeger Tracing in TruBudget.
