### ISSUE TITLE
ui: Prohibit root user from adding projects/subprojects/workflow items

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#39]
In GitLab by @mathiashoeld on Oct 11, 2018, 10:40

Current: Root user can add projects and subprojects and only when a workflow item is added, an error is thrown. (Missing assignee error, although there is an assignee set)

Should be: Root user cannot add projects, subprojects or workflow items and a fitting error message should be displayed

**Comment by mathiashoeld** [comment]
relates to #366

**Comment by miamarina** [comment]
relates to #369

**Comment by mathiashoeld** [comment]
Issue is split into: 

- [ ] Projects: #379
- [ ] Subprojects: #378 
- [ ] Workflowitems: #380

**Comment by Stezido** [comment]
I close this Issue due to all separated issues are closed.
