### ISSUE TITLE
Inputfield Labels are over-flowing

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#4]
In GitLab by @gonzochic on Oct 2, 2017, 09:55

Inputfield Labels are sometimes overflowing for french-translations. I think the only thing we can do right now is to simply make the fields a bit wider. Not the best solution but should work for now.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Apr 12, 2018, 11:36

moved from kfw-chain-frontend#79

**Comment by gonzochic** [comment]
Closed due to inactivity
