### ISSUE TITLE
ui: Refactor passing user objects instead of user ids

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#407]
### Description
To only way to get the displayName of a user/group the userlist fetched when logging into Trubudget. If a component needs to view the displayName but only has the id the render method has to iterate over the userlist for every userId. 

### Suggestion
This can be avoided if users are passed as objects with id and displayname params instead of the user id only.

**Comment by georgimld** [comment]
This issue was solved already so it will be closed
