### ISSUE TITLE
api: response code 500 when trying to create a closed workflowitem

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#411]
### Description

When calling the endpoint /subproject.createWorkflowitem with following body ...
```code 
{
	"apiVersion": "1.0",
	"data": {
		"projectId": "{{projectId}}",
		"subprojectId": "{{subprojectId}}",
		"displayName": "b",
		"amount": "1",
		"currency": "EUR",
		"amountType": "disbursed",
		"status": "closed"
	}
}
```
... the response looks like this:
```code
{
    "apiVersion": "1.0",
    "error": {
        "code": 500,
        "message": "Assertion: This is a bug."
    }
}
```

Obviously the api should be able to handle creating a workflowitem with status code closed.

### Suggestions
1. It should not be possible to create a closed workflowitem. 
-> Remove status field from body of createWorkflowitem endpoint
2. It should be possible to create a closed workflowitem.
-> Investigate the 500 response and handle the closed status

**Comment by mathiashoeld** [comment]
IMHO it should *not* be possible to add closed workflowitems because it should be evident who closed the workflowitem. also the workflowitem can be closed using a dedicated endpoint and we should not introduce some "magic" by letting the user create closed workflow items.
