### ISSUE TITLE
bc: Improve logs when trying to connect with a diverged blockchain

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#417]
### Description
When connecting to an existing trubudget network with a local multichain instance which state is different from the networks multichain state the logs don't give information about whats happening. The node is ready and connected although it has a different mutlichain state.

### Implementation
Improve logging by printing out information that the networks multichain state is different, that it cannot be synced and that the local state is used instead.

### Suggestion
Could be added with #190

**Comment by Stezido** [comment]
@SamuelPull what's the current status?

**Comment by SamuelPull** [comment]
@Stezido I thought I was stuck but I am definitely stuck

**Comment by daniel-arnauer** [comment]
Teste case: Slave node and master node are same state (after provisioning) then both nodes are edited separately by adding one project to each node with different name. The result: one transaction is rejected

This logging is provided by the new logging feature

![image](https://user-images.githubusercontent.com/59825636/140079569-63e9b565-27c6-4991-b466-5ea1581c23d2.png)
