### ISSUE TITLE
Change timestamp in history

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#426]
Instead of "2 hours ago" the timestamp of history items should display year, month and day of the occurrence.

**Comment by daniel-arnauer** [comment]
Possible Solution: 
Remove "fromNow()" in HistoryList.js to get absolute date

Question: Should this change also applied for notifacations (NotificationListItems.js) ?

**Comment by daniel-arnauer** [comment]
Qick Solution:

Change 
`secondary={dayjs(eventTime).fromNow()}`
to
`secondary={dayjs(eventTime).format("MM.DD.YYYY HH:MM")}`

Should the format depend on selected language?

**Comment by mathiashoeld** [comment]
> Quick Solution:
> 
> Change
> `secondary={dayjs(eventTime).fromNow()}`
> to
> `secondary={dayjs(eventTime).format("MM.DD.YYYY HH:MM")}`
> 
> Should the format depend on selected language?

this should suffice. please also update the format of the messages as well.

**Comment by Stezido** [comment]
We should only display day, month and year since a exact timestamp is not important and it's easier to handle according to time shifts
