### ISSUE TITLE
Test the email-notification feature

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#445]
### Description
A few tests are not done yet. Following tests shall be executed and results shall be shared:

- [ ] load test of mutlichain-feed/whole email notification workflow
- [ ] test different databases
- [ ] Include a email-service instance to e2e-tests

**Comment by Stezido** [comment]
See #478 for more details about `Include a email-service instance to e2e-tests`

**Comment by mayrmartin** [comment]
Related to #835
