### ISSUE TITLE
Right for "Closing / Approving a workflow" should only be possible for one assigned person 

### ISSUE THREAD

**Issue by SophieKettler** [openkfw/TruBudget#465]
When the business administrator sets up a new project / subprojects / workflows, he is technically able to give himself the right to close (approve) a workflow (ex. Project Manager of the Partner country institution), although the workflow should be only closeable (approved) by another person (ex. Transaction Manager of donor) that he needs to assign beforehand.

**Comment by Stezido** [comment]
fixed in #593
