### ISSUE TITLE
Fix npm audit issue

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#485]
Npm audit is currently failing due to the package `http-proxy`. As soon as a fix is available, perform an update of the package. For information see here: https://www.npmjs.com/advisories/1486

Relatest to https://github.com/http-party/node-http-proxy/issues/1446

**Comment by Stezido** [comment]
Workaround for current PRs: 
set npm audit production flag in travis.yml so that tests can be executed
