### ISSUE TITLE
Log helpful error message when a user tries (and fails) to log-in on another organization's node

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#51]
In GitLab by @kevinbader on Dec 14, 2018, 18:10

Currently, TruBudget logs an Internal Server Error caused by not being able to decrypt the user's private key.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 31, 2019, 12:14

removed milestone

**Comment by Stezido** [comment]
duplicate #174
