### ISSUE TITLE
Sign/Encode directory hash on Backups

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#53]
In GitLab by @saschak_94 on Dec 17, 2018, 16:02

When creating backups we just create a hash over the directory. A person that wants to harm your system can do that too. It would make sense to sign/encode the hash with a secret to add another layer of security.

Additionally, if a backup with an invalid hash is submitted, it still resides in a temporary folder. The backup should be deleted if it is invalid.

**Comment by phpai** [comment]
In GitLab by @saschak_94 on Dec 17, 2018, 16:02

changed title from **Sign/Encode directory {-H-}ash on Backups** to **Sign/Encode directory {+h+}ash on Backups**

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Dec 18, 2018, 11:14

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 31, 2019, 12:14

removed milestone

**Comment by mathiashoeld** [comment]
backup feature is discontinued

**Comment by mathiashoeld** [comment]
see #227
