### ISSUE TITLE
[Low criticity] Easing the acess to the header of the main screen

### ISSUE THREAD

**Issue by a-dossa** [openkfw/TruBudget#579]
As more and more project will be integrated in Trubudget, the list of project users will see on a the first screen of TruBudget will increase.
As a consequence, users will scroll down more and more after time to find their projects and will have to scroll up every time they want to go back to the header.

In other to avoid this, we propose to give a way to have an easy access to the header area (see image attached)
 as you scroll down.

Two wayS identified to do so : 

1. Add a button "go back at the top of the screen"

2. Fix the header text as the first line of an Excel sheet can be fixed (see file attached)

[fixed header area.xlsx](https://github.com/openkfw/TruBudget/files/5422130/fixed.header.area.xlsx)

<img width="950" alt="header area" src="https://user-images.githubusercontent.com/72857322/96862142-5e395480-1465-11eb-9224-fb0aaa035152.PNG">

**Comment by georgimld** [comment]
Thank you for the proposed solutions. After talking to my colleagues we decided to implement the first suggestion and this fix will be present in the next release.
