### ISSUE TITLE
[High criticity] Problem: Permission management is still largely too complicated,   confuses project users at partner country institutions and needs to be   simplified (problem also know from Burkina Faso).             

### ISSUE THREAD

**Issue by a-dossa** [openkfw/TruBudget#581]
Permission management is still largely too complicated, confuses project users at partner country institutions and needs to be   simplified (problem also know from Burkina Faso).

Needs for the Basket financing:    

1. The creator of a workflow item in the partner country must systematically not have the right to validate the workflow item, but both creator and assignee of a workflow item should systematically have the right to modify the workflow item (upload document, amount assigned/disbursed/paid) as long as it is not closed. Partner country should not even be able to choose between general or restricted workflow item type.          

2. For a given subproject, the donor should systematically be the assignee (validator) for every workflow item          

Possible solutions:     

- Allow to define restricted/general type of workflow on sub project level   (when creating the subproject), applying to all workflow elements of the   subproject? Could also have the option "define on workflow item   level".     

- It should be mandatory to choose the assignee (validator) at the moment of workflow item creation, and not after.     

- Allow to define on subproject level (when creating the subproject), whether the assignee (validator) for all workflow items is systematically the same and if yes select the assignee. Could also have the option "define   on workflow item level".

**Comment by Stezido** [comment]
This issue should be solved by applying the solution described in #572

**Comment by Stezido** [comment]
Fixed in #572
