### ISSUE TITLE
Add avatars to users

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#6]
In GitLab by @saschak_94 on May 3, 2018, 08:21

Currently it is not possible to display users with their avatars on the frontend.
To solve the problem we need to store the avatar with the user on the chain.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 25, 2019, 11:03

unassigned @kevinbader

**Comment by kevinbader** [comment]
it could make sense to store this off-chain per privacy concern, related to #77
