### ISSUE TITLE
Document runtime and operations architecture

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#61]
In GitLab by @kevinbader on Jan 15, 2019, 13:12

Relate to the Blockchain Reference Architecture

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 15, 2019, 13:12

@gonzochic FYI

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 15, 2019, 13:14

@phpai IIRC there is already some operations architecture documentation available. Any thoughts on TODOs in that regard?

**Comment by phpai** [comment]
In GitLab by @kevinbader on Jan 31, 2019, 12:14

removed milestone

**Comment by Stezido** [comment]
The documentation regarding Trubudget's operation/administartion can be found in the [admin section](https://github.com/openkfw/TruBudget/blob/master/docs/operation-administration/introduction.md) or on our [website](https://openkfw.github.io/trubudget-website/docs/operation-administration/introduction)
