### ISSUE TITLE
bc: Encrypt the connection between nodes - 1003SP

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#611]
### Description
Currently blockchain nodes are connected unencrypted. Trubudget force the admin user who sets up Trubudget to take care of it with e.g. VPN.
Sometimes Trubudget's admin users are not able to take care of it theirself so we need a solution that comes with the blockchain Trubudget project/image. This solution might be en/disabled as required.

### Solution
?

**Comment by mayrmartin** [comment]
Closed. Related to solved by #831
