### ISSUE TITLE
e2e-tests: Add ROOT_SECRET environment variable

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#633]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently the passwort of the root user (ROOT_SECRET) is hardcoded and cannot be changed. Adding an env variable to set a custom ROOT_SECRET  would prevent tester issues while setting up the e2e-test locally.

**Comment by m-janos** [comment]
@galethil  After running `sh scripts/testing/start-e2e-tests.sh` Cypress cannot connect to the API.

API container log:
```
Problem with establishing connection to min.io and creating bucket.
Error during searching for bucket Error: getaddrinfo ENOTFOUND nginx
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'nginx'
}
```
