### ISSUE TITLE
Workflow item type not working when a validator is selected

### ISSUE THREAD

**Issue by Malick-Niang** [openkfw/TruBudget#636]
Once a "validator" is selected on subproject level, the workflow item type does not seem to work anymore. 

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

For both "Restricted" and "General" workflow items (as defined on subproject level or on workflow item level if selected "any" on subprojecet level), the definition seems to be: the creator exclusively keeps all write and admin rights (except of course validation, which is with the validator).

## Expected Behavior 🤔

It should be:

·       If general: BOTH creator and validator can modify information (i.e. have all admin and write rights except "validation" right, which is reserved for the validator) until validation of workflow item

·       If restricted: ONLY the validator can modify information until validation of workflow item

When validator is changed during workflow item creation: Restricted / general : No difference, creator still has exclusive write and admin rights (except validation)

When validator is not changed during wokflow item creation but selected AFTER workflow item creation:

o   Restricted workflow items: work as before - all write and admin are transferred exclusively to the validator and creator is deprived of write and admin rights

o   General workflow items: work as before - all write and admin rights (except validation) remain exclusively with the creator 

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |

frontend | 1.16.0 | 
api | 1.16.0 | 
blockchain | 1.16.0 |
multichain | 2.0.1 | 
emailService | 1.16.0 |
exportService | 1.16.0 |

**Comment by Stezido** [comment]
Ty, for reporting this bug. We already fixed it in #662.
