### ISSUE TITLE
Validator feature is not working as expected

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#643]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description

 - Info button for workflow item type to be defined on subproject level: explanations are in French, even if logged in in English
 - Validator drop down list (as any other dropdown list): Should have the search/filter function as otherwise complicated to find user
 - Define workflow item type "restricted" on subproject level -> When creating a workflow item, information button at "workflow item type": Is in French although logged in in English, and wrong information (about "don't submit personal information", I think this is meant for the user creation page)
 - When no "validator" is selected on subproject level, during workflow item creation, the field "validator" (or assignee) lacks a label; there is only a dropdown list not clear to the user what it is.

### Subproject with validator:

Once a "validator" is selected on subproject level, the workflow item type does not seem to work anymore. For both "Restricted" and "General" workflow items (as defined on subproject level or on workflow item level if selected "any" on subproject level), the definition seems to be: the creator exclusively keeps all write and admin rights (except of course validation, which is with the validator). It should be:
If general: BOTH creator and validator can modify information (i.e. have all admin and write rights except "validation" right, which is reserved for the validator) until validation of workflow item
If restricted: ONLY the validator can modify information until validation of workflow item
 

### Subproject without a validator

When validator is changed during workflow item creation: Restricted / general : creator still has exclusive write and admin rights (except validation), as in the case above where a validator has been defined on subproject level
When no validator is changed during workflow item creation but selected AFTER workflow item creation:
Restricted workflow items: work as before the new release - all write and admin are transferred exclusively to the validator and creator is deprived of write and admin rights
General workflow items: work as before the new release - all write and admin rights (except validation) remain exclusively with the creator

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| Trububudget| v1.16.0  |
| Browser | Chrome|

**Comment by daniel-arnauer** [comment]
Task 1
Check why the string in workflowitem-type tooltip do not change language after changing language at Loginpage and fix it

Task 2
Use a component with searchfield and single user selection for setting the validator in subproject creation dialog

Task 3
Check wrongly used language string at tooltip for workflowitem-type at subproject creation dialog and fix it

Task 4
Add a label "Validator" to the validator field at workflowitem creation dialog. This label must be also displayed if the assignee is pre-set(The assignee is pre-set with the validator of the subproject if existing)

**Comment by Stezido** [comment]
### Tasks:
- Change validator behaviour

Creator=Creator of a workflowitem
Validator= If set the validator is automatically set as assignee on workflowitem creation and can close workflowitems instead of the assignee

**Notes:** 
- The close permission was removed with the latest release, so only the assignee or the validator (if set) are able to close a workflowitem

| Validator set | Workflowitem Type | Behaviour|
| ------------- | ------------- | --------------------|
| no                | any               | workflowitem type can be selected on workflowitem creation |
| no                | general         | Creator only gets all permissions|
| no                | restricted     | Only the assignee has all write/admin permissions, Creator gets view permissions if he/she is NOT the assignee
| yes               | any               | workflowitem type can be selected on workflowitem creation, On workflowitem creation the validator is automatically set as assignee, Only the validator can close workflowitems instead of the assignee |
| yes               | general        | On workflowitem creation the validator is automatically set as assignee, Only the validator can close workflowitems instead of the assignee Creator gets all permissions|
| yes               | restricted     | Only the validator gets write/admin permissions, this cannot be modified

**Comment by daniel-arnauer** [comment]
Some issues are duplicated:
#647 
#635

**Comment by Stezido** [comment]
For the final solution regarding the "validator" (now assignee on workflowitem level) see #662
