### ISSUE TITLE
Wrong information displayed in workflow item type

### ISSUE THREAD

**Issue by Malick-Niang** [openkfw/TruBudget#647]
Define workflow item type "restricted" on subproject level -> When creating a workflow item, information button at "workflow item type": Is in French although logged in in English, and wrong information (about "don't submit personal information", I think this is meant for the user creation page)

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1. Browser language set to "French"
2. Application language set to "English"
3.
4.

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| Frontend       | v1.?.?  |
| API            | v1.?.?  |
| Blockchain     | v1.?.?  |
| Export-Service | v1.?.?  |
| Email-Service  | v1.?.?  |
| Chrome-Browser | ?       |
| etc.           |         |

**Comment by SamuelPull** [comment]
<img width="433" alt="Screenshot 2020-11-26 at 11 58 07" src="https://user-images.githubusercontent.com/26326794/100342736-b58b9100-2fde-11eb-85c7-23f8eebd75df.png">
<img width="520" alt="Screenshot 2020-11-26 at 11 57 59" src="https://user-images.githubusercontent.com/26326794/100342738-b6242780-2fde-11eb-8a39-697d6f5e4f8c.png">
