### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#65]
In GitLab by @moise.djanhan on Jan 27, 2019, 22:40

Send out notifications via Email

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Jan 31, 2019, 14:57

Send every notification from Trubudget via E-Mail - possibly new service needed.

**Comment by phpai** [comment]
In GitLab by @jzakotnik on Feb 1, 2019, 10:11

changed title from **{-[BF] E-}mail notifications** to **{+e+}mail notifications**

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 13:58

This issue relies on issue 346 (extend user profile -> email address). Strong demand, so if this is easily implemented lets put it on high prio -> Quick win

**Comment by mathiashoeld** [comment]
Issue relies on #77 - email address in user profile needed
