### ISSUE TITLE
Fix eslint issues

### ISSUE THREAD

**Issue by galethil** [openkfw/TruBudget#672]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Continuously enable disabled eslint rules and then fix issues in code.

## Motivation 🔦

Improve code quality without need for large pull request that can disrupt development.

**Comment by SamuelPull** [comment]
Resolved in https://github.com/openkfw/TruBudget/pull/673
