### ISSUE TITLE
Actions table of confirmation dialog is misaligned

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#677]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If I create a workflowitem with a long subproject or project name and select an assignee who has no view permissions on the project/subproject, the additional actions table ihn the confirmation dialog is misaligned. 

## Expected Behavior 🤔

Every cell in the action tables of the confirmation dialog can be read easily and are not misaligned

**Comment by daniel-arnauer** [comment]
A Screenshot of the problem:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/59825636/101616124-4450d280-3a0f-11eb-9f36-6f0c9d273d3e.png)
