### ISSUE TITLE
[TECHNICAL] api: Eslint setup for import rules to mimic TypeScript Hero VS Code extension

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#686]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Configure eslint import rules to conform to TypeScript Hero import sort to ensure a consistent import ordering and empty lines between import "groups".

## Motivation 🔦

Using import/first and import/order rules out of the box results in a different ordering than used and intended in the application. Tweaking it to behave like TypeScript Hero ordering should be piece of cake.

**Comment by galethil** [comment]
Not valid anymore
