### ISSUE TITLE
excel-export-service: Validate requests with joi

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#692]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

All endpoints of the excel-export-service service are not validated. As done in the Trubudget api `joi` can be used for validation.

- [ ]  /health
- [ ] /readiness
- [ ] /version
- [ ] /test/download
- [ ] /prod/download

**Comment by daniel-arnauer** [comment]
There are no joi validations needed since none of the requests require any parameters, they just require a valid URL

**Comment by Stezido** [comment]
Since there are no parameters to validate in each of the listed endpoints, the issue is closed.
