### ISSUE TITLE
[TECHNICAL] Dependencies ini and find-my-way have security issues - 1SP

### ISSUE THREAD

**Issue by galethil** [openkfw/TruBudget#721]
🔧
** Technical Issue should generally not alter any behavior of the application. This category is used for issues not requiring any functional/business requirements such as technical debt, refactoring, formatting, ESLint compliance, adding required libraries or removing unused libraries, efficiency tweaking.**

**What is the current state of things?** 🔬
Dependencies ini and find-my-way have security issues and should be updated.

**Describe the solution and its added value** 🔩
Update of packages.

**Comment by SamuelPull** [comment]
This issue seems to have been fixed, and can be closed?

**Comment by Stezido** [comment]
> This issue seems to have been fixed, and can be closed?

Yes, it's fixed.
