### ISSUE TITLE
UI: Two scroll bar appear in Assignee drop down

### ISSUE THREAD

**Issue by pheolink** [openkfw/TruBudget#722]
Description:- Two scroll bar appear in Assignee dropdown in "Set permission for payment interim installment".

![image](https://user-images.githubusercontent.com/18503748/104304806-270a9a80-54cc-11eb-82d5-0bf8cd659158.png)

**Comment by daniel-arnauer** [comment]
![image](https://user-images.githubusercontent.com/59825636/104310591-3f7eb300-54d4-11eb-9704-30f1a0f81e28.png)
