### ISSUE TITLE
User selection in group editing has an api call for each selection - SP 0.5

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#725]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Each time a user is selected or deselected using the checkbox in the dialog, an api call for group.addUser or group.removeUser is bein sent. 

## Expected Behavior 🤔

Users to be added and removed should be stored (e.g. in an array), and the requests should only be sent when clicking the "Done" button.

## Steps to Reproduce 🕹

Steps:

1. open the edit dialog of a group
2. click on the dropdown for selecting users
3. try to select or deselect users and look at what calls are being sent

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| TruBudget       | v1.17.0  |

**Comment by daniel-arnauer** [comment]
Closed by https://github.com/openkfw/TruBudget/pull/811
