### ISSUE TITLE
deployment: add load tests and include in ci

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#73]
In GitLab by @phpai on Jan 28, 2019, 17:37

To better see the impact of code changes on the performance, we should add load testing to our test suite

**Comment by phpai** [comment]
In GitLab by @phpai on Jan 31, 2019, 10:31

changed the description

**Comment by phpai** [comment]
In GitLab by @phpai on Jan 31, 2019, 10:32

changed title from **deployment: {-include load test-} in ci** to **deployment: {+add load tests and include+} in ci**

**Comment by mayrmartin** [comment]
Duplicate of #835
