### ISSUE TITLE
[TECHNICAL] Update documentation for release

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#734]
🔧
** Technical Issue should generally not alter any behavior of the application. This category is used for issues not requiring any functional/business requirements such as technical debt, refactoring, formatting, ESLint compliance, adding required libraries or removing unused libraries, efficiency tweaking.**

**What is the current state of things?** 🔬
Release documentation is obscure and could be updated.

**Describe the solution and its added value** 🔩
A clear documentation.

**Comment by Stezido** [comment]
Since the release documentation is only important for the internal team. I suggest we do not push it to the github repo.
