### ISSUE TITLE
Add connection status to network list - 8SP

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#746]
## Summary 💡

Add a column to the network table which shows the connection status of a node and if not connected the last seen timestamp

# Subtasks 🔗
 * [ ] Show node connection status -  [PR](https://github.com/openkfw/TruBudget/pull/775)
 * [ ] Display last available timestamp #774

**Comment by m-janos** [comment]
@Stezido Clarification needed. Each network can contain multiple nodes. If connection status for each node should be displayed, the UI has to be modified. Do we have know how it should look like? Some expandable row or just write all node statuses in single row?

**Comment by m-janos** [comment]
Proceed to the subtask after [PR](https://github.com/openkfw/TruBudget/pull/775) is closed
