### ISSUE TITLE
Developer-Setup.md outdated

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#782]
## Description 😯

With the addtion of DMS (minio) developer setup guide is out of date.
When trying to run TruBudget, according to the guide, developer ends up with application that is not working.
AFAK, at least minio module and envrionmental variables are missing.

## Steps to Reproduce 🕹

Steps:

1. Start TruBudget by the developer setup guide
2. 🚫

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| Frontend       | v1.?.?  |
| API            | v1.?.?  |
| Blockchain     | v1.?.?  |
| Export-Service | v1.?.?  |
| Email-Service  | v1.?.?  |
| Chrome-Browser | ?       |
| etc.           |         |

**Comment by Stezido** [comment]
The developer setup is updated in #840.
