### ISSUE TITLE
Change password option

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#79]
In GitLab by @jzakotnik on Feb 1, 2019, 10:21

This is important for user management or e.g. changing password at first login

**Comment by phpai** [comment]
In GitLab by @kevinbader on Feb 20, 2019, 11:52

assigned to @mathiashoeld

**Comment by gonzochic** [comment]
Could be done together with #77

**Comment by mathiashoeld** [comment]
Checklist: 

- [ ] New intent
- [ ] New event
- [ ] New domain & service + Test
- [ ] UI component & E2E test
- [ ] Documentation 
- [ ] Changelog
