### ISSUE TITLE
[TECHNICAL] Run Cypress E2E Test in Docker and in Interactive Mode

### ISSUE THREAD

**Issue by m-janos** [openkfw/TruBudget#795]
🔧
With possibility to run the application and E2E tests with Docker Compose in one time, there is a question to run Cypress in interactive graphical mode for running selected tests/suite. Docker does not support running graphical applications directly therefore additional tools needed depending on the used operating system. E.g. for system based on Unix a running X11 graphical server and port forwarding to its socket are required.

**What is the current state of things?** 🔬
 * E2E tests with Docker Compose are run in command line mode, this is good, but not always needed when only one test suite / test is needed at the time

**Describe the solution and its added value** 🔩
 * This represents the adaption to run Cypress in the interactive mode as describe in the [documentation](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/#header).
 * Decreased development time
 * Solution depends on the operating system. Description of needed steps and tools for Mac OS can be found [here](https://sourabhbajaj.com/blog/2017/02/07/gui-applications-docker-mac/) and [here](https://cntnr.io/running-guis-with-docker-on-mac-os-x-a14df6a76efc).

**Comment by m-janos** [comment]
Associated branch: 795-e2e-doc-compose-gui

**Comment by Stezido** [comment]
Since the recommended way to use cypress is npm not docker, we decided to skip the setup of cypress GUI in docker.
