### ISSUE TITLE
api: Print specific error message when not all needed environment variables are set

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#81]
In GitLab by @mathiashoeld on Feb 4, 2019, 10:25

When starting the api without setting the environment variables (Contributer-Guide.md#api) (in dev mode) the app just crashes without notice of what went wrong, e.g.
```
[2019-02-04 09:21:48.297 +0000] WARN  (TruBudget on AMAC02X97R8JG5J):
    msg: "Warning: root password not set; autogenerated to d0067edf073e5d349011587091839d65ab3e170c2ebccea7e549b60cd9be2a65"
[nodemon] app crashed - waiting for file changes before starting...
```

Expected behaviour: The api should print a message stating why it crashed by logging a `fatal` message with the reason.

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Feb 4, 2019, 10:26

changed the description

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Feb 4, 2019, 10:30

e.g. the environment variable `ORGANIZATION` has to match the one set in the `docker-compose.yml` of the blockchain, which is currently `ORGANIZATION = KfW`

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 15:24

changed the description

**Comment by mathiashoeld** [comment]
Error messages for `ORGANIZATION` and `ORGANIZATION_VAULT_SECRET` are printed as expected and the `ROOT_SECRET` is set to a random value if not provided by the user. 

Since this is the expected behaviour, this issue will be closed.
