### ISSUE TITLE
Code quality/security analysis SP 5

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#836]
## Summary 💡
Integrate quality/security analysis into ci/cd

## TODOs
- Check quality/security analysis tools
- Check sonarqube for quality analysis
- Check code ql for security analysis
- Integrate quality/security analysis into ci/cd

**Comment by mayrmartin** [comment]
Successfully integrated in private CI/CD. Results will be analyzed and published in the documentation in the next release (1.25.0).
