### ISSUE TITLE
Documentation has broken link for Permissions

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#885]
Have a look at https://github.com/openkfw/TruBudget/blob/master/doc/wiki/User-Guide/Permissions.md which is referenced in the docs folder. I think it needs to point to the wiki?
https://github.com/openkfw/TruBudget/blob/master/doc/User-Guide/wiki/User-Guide/Permissions.md

**Comment by georgimld** [comment]
The https://github.com/openkfw/TruBudget/blob/master/doc/ folder is depracated, it will be deleted and the new documentation folder will be https://github.com/openkfw/TruBudget/tree/master/docs, where all broken links will be fixed (with #886)
