### ISSUE TITLE
Increase the size of User.ID field (currently 3̶2̶-̶c̶h̶a̶r̶ 50 ) to 64-char

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#887]
### Discussed in https://github.com/openkfw/TruBudget/discussions/861

<div type='discussions-op-text'>

<sup>Originally posted by **josenogueiradalmeida** May  6, 2019</sup>
During our tests, we noticed that we can not fill the User ID with one of our client's email (monique.bendahan@fas-amazonas.org). 

For this reason, we kindly ask to increase the size of the field to support 64 characters.

Thanks in advance.</div>

**Comment by SamuelPull** [comment]
Issue is not the length of login ID. Some of the examples are shorter than 32 characters.
"@" (char code 64) and "." (char code 46) are not allowed by validation regex /^([A-Za-zÀ-ÿ0-9-_]*)$/

**Comment by georgimld** [comment]
We decided to not allow special characters like "@" in the usernames, so just increasing the user.id size should be sufficient
