### ISSUE TITLE
Default approval-group for workflowitems

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#89]
In GitLab by @kevinbader on Feb 19, 2019, 15:49

From our discussion on Slack, @jnogueira:

> we [..] need one meta-data field, that is the default approval-group for new workflowitems. [..] the user that is creating a subproject can select a default approval-group [..] that every workflowitem created for this subproject can be approved/closed by [..]. It is an optional field: in case the user does not define it, the user that creates the workflowitem is the user that has this permission to approve/close the workflowitem.

This seems related to other requests for permissions-related convenience features, e.g., #339 or #187.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Feb 20, 2019, 11:52

assigned to @mathiashoeld

**Comment by mathiashoeld** [comment]
AFAIK the underlying problem was solved differently, so there is no need for a default approver group anymore. If this is not the case, feel free to re-open the issue.
