### ISSUE TITLE
Update Demo Sandbox data - provisioning script

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#897]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

The demo data when spawning and provisioning an instance of trubudget is somewhat difficult to grasp. This FR changes the demo data.

**Comment by Stezido** [comment]
Do you mean  the provisioned data has to be changed so the content makes more sense?

**Comment by jzakotnik** [comment]
Ah, I only created the issue to link it to the respective branch. Xaver and I updated it already (see PR)
