### ISSUE TITLE
Trubudget-Website Bug

### ISSUE THREAD

**Issue by laurenzhonauer** [openkfw/TruBudget#908]
## Description 😯
1. The Page https://openkfw.github.io/trubudget-website/ can be viewed in dark Mode.
Some Texts do not have a new color in dark mode and can only be read poorly.

<img width="1436" alt="contrast" src="https://user-images.githubusercontent.com/44588135/128210183-844e1987-3351-4f9d-bf85-26c44a276d7b.PNG">

2. The Pages about bare-metal setup [connect to existing node](https://openkfw.github.io/trubudget-website/docs/operation-administration/installation/connect-to-existing-node/bare-metal) and [create new network](https://openkfw.github.io/trubudget-website/docs/operation-administration/installation/create-new-network/bare-metal) both have a link about installing necessary software on your own machine in the first paragraph. The Links in the first page leads to the second and the other way around, this seems like a mistake since both links say that they lead to a manual for installing software.

3. In the [Developer Setup](https://openkfw.github.io/trubudget-website/docs/developer/developer-setup#ide) there are several vs code extensions listed.
    * eg2.tslint is marked as deprecated, but there is an alternative from Microsoft : ms-vscode.vscode-typescript-tslint-plugin
    * ZeroDragon.prettylintednode cannot be found in the vscode markedplace anymore

## Your Environment 🌎

https://openkfw.github.io/trubudget-website/

**Comment by mayrmartin** [comment]
Regarding documentation issue (wrong links, developer setup): will be solved in this repository via #909
Regarding dark mode: this issue will be solved in theopenkfw/trubudget-website repository. The according issue is [this](https://github.com/openkfw/trubudget-website/issues/6).
