### ISSUE TITLE
bump-tag-version script does not update the version

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#911]
- [x ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
When running the `bump-tag-version` the script does not update the version. It only executes `npm install` in each sub-project.

### How to reproduce 🕹
Execute `bump-tag-version.sh v1.25`  in every `package.json` the version should be 1.25.

**Comment by daniel-arnauer** [comment]
this is a bash file:
`bash bump-tag-versions.sh v1.25`
works properly

**Comment by daniel-arnauer** [comment]
Solution: Since we always use bash in our `.sh` scripts (Implied by`#!/bin/bash` in the first line), I change the documentation from `sh bump-tag-versions.sh` to `bash bump-tag-versions.sh`
