### ISSUE TITLE
Improve logging in the api

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#916]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

The api needs to have a better error logging in order to provide more info when something goes wrong.

### Example: 
For example in this case no explanation was given as to why the api couldn't create the organization stream. After much debugging it was found that the ORGANIZATION_VAULT_SECRET was not correct - this should have been logged appropriately
![Screenshot 2021-08-06 at 13 50 47](https://user-images.githubusercontent.com/48566702/128521029-8bcee711-7264-4f4b-866f-15967f9a9834.png)

**Comment by laurenzhonauer** [comment]
Will be covered by #940
