### ISSUE TITLE
Assign permission dialog assigns permission to user and group

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#943]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
Workflowitem assign permission assign permission to user and group when a user & a group have the same name.  The API does not assign additional permissions (case workflowitem)

1. Create a user
2. Create a group with the same name as the username (& assign the user to the group)
3. Choose any project / sub-project / workflowitem
4. Assign permissions to the user or the group. Both fields for user and group will be checked in the permission dialog

**Comment by Stezido** [comment]
Option 1 : disallow creating group/user with same name
Option 2 : allow it and check the code base for missing group handling / user/groups bugs
