### ISSUE TITLE
Add a search functionality to the UI "List of projects"

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#95]
In GitLab by @lennart.ploen on Feb 25, 2019, 18:23

**Objective**: Introduce a search field to facilitate access to a specific project in a long list of projects

**Purpose**: As the list of projects will be ever growing, and some users will have access to all projects, a search functionality will help the user find and access a specific project

**Concept**
- Introduce a search field at the top of the screen where the user can freely type keywords of what she is looking for.
- The search functionality should search data fields on all available levels (project, sub-project, workflow)
- Alternative A : Once you hit "enter", the list of projects should be updated, only showing those projects where the keyword has been found
- Alternative B : A dropdown list shows clickable links to the place where the keyword has been found; 
- Alternative C : An alternative/ complement to the search functionality would be a sorting functionality putting the list of project into a specific order (by date of creation, by date of last modification, alphabetical order of project name, ...)

**Risks**: Prioritize alternative which works quickly even with very slow internet connection

[190225_Search.pptx](https://github.com/openkfw/TruBudget/files/3002317/190225_Search.pptx)

**Comment by Stezido** [comment]
We are going to add tags to implement a search functionality. #157

**Comment by gonzochic** [comment]
Will be implemented in #157
