### ISSUE TITLE
e2etests are NOT running stable (SP 3)

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#958]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

The e2e-tests are failing randomly because of several issues:
- `OOM`
- `works on my machine`
- `timing issues caused by cy.wait`
- `not supported by the used browser`

## Suggestion

Update Cypress to the latest version

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| E2E-Tests| v1.24.0 |

**Comment by laurenzhonauer** [comment]
In case a follow up issue regarding performance will be opened.
This could come in handy: https://docs.cypress.io/guides/guides/parallelization#Overview
