### ISSUE TITLE
Express project budgets in local currency in UI "List of projects"

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#97]
In GitLab by @lennart.ploen on Feb 26, 2019, 11:14

**Objective**: Express project budgets in a standard currency to allow for (1) budgets co-financed through multiple currencies and (2) comparability between project budgets

**Purpose**: Many projects are co-financed through the state (national currency) and one or several donors (international currencies). In order to show a total project  budget, amounts must be translated into one single currency.

**Concept**: Prioritizing local requirements and simplicity, we would choose alternative 1 from the following list of alternatives: 

| #| Alternative| Pro | Con |
| :------: | :------: | :------: | :------: |
| 1| Translate all amounts into local currency (see issue 333 and 194) and express total project budget exclusively in local currency in the UI "List of projects" | Alternative preferred by Burkina actors, as local financial management software uses local currency| Donors don't see budget in their preferred currency|
| 2| Don't show total project budget, but individual financing amounts in original currency in the UI "List of projects"| Donors will find their budget in original currency| Risk of overloading UI, Burkina does not see budget in preferred currency|
| 3| Translate all amounts into various currencies (see issue 333 and 194), and allow user to express total project budget in the currency selected by the user. Needs a drop-down menu button to select the currency.| Burkina and donors wishes respected| Implementation complexity|
| 4| Don't show any project budget amount in the UI "List of projects"| Easy to implement and lightens UI| Users won't see project budgets in UI "List of projects" but within each project|

[190226_UI_projects_currency.pptx](https://github.com/openkfw/TruBudget/files/3002313/190226_UI_projects_currency.pptx)

**Comment by mathiashoeld** [comment]
some of this was already solved, see #202
