### ISSUE TITLE
Allow user to distinguish financing sources and add other project attributes when adding a new project

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#99]
In GitLab by @lennart.ploen on Feb 26, 2019, 15:15

**Objective**: Add additional data fields in the window "add new project"

**Purpose**: Additional data fields to be entered when adding a project should allow for distinguishing sources of finance, search/filter for a specific project in the UI "List of projects" (see issue 371) by searching for project attributes, eventually allow for more detailed data analytics on TB, and automate processes on TB.

**Concept**: All proposed data fields below should be filled in when adding a new project. All this data already exists in existing software, so via integration the data can be entered automatically in TB.

The following data is to be displayed in the upper part of UI "project" (issue will be specified):
- Name of source of finance (Donor name or State from dropdown menu) 
- Amount of source of finance 
- Currency of source of finance (from dropdown menu)

A button should allow to add an additional source of finance (and associated amount, contract code and currency)

The following project attributes are to be displayed exclusively in the meta-data info field (issue 368, tbc):
- Project code: A unique identifier of the project allows existing software to exchange data with TB for a given project. A project code is more reliable than a project name as a unique identifier. 
- Financing contract code: A given donor might finance a project through contract 1 at the beginning of the project and sign a contract 2 for the same project later on, so you might distinguish several contracts for one donor.
- Managing structure (Name of line ministry in charge of project) : Especially if no internal processes will be shown in the workflow, it might still be interesting to know which structure is in charge of the project.  
- Programme budgétaire: Every project is associated to a programme budgétaire in existing software.  
- Action: Every project is associated to an action in existing software.
- Activité: Every project is associated to an activité in existing software.	

**Risks**: 
- Verify whether an automatic data entry through integration with existing software in Burkina Faso is possible with the meta data fields
- If attributes are considered too internal, difficult to implement and/or not necessary for the search or analytics function, we should drop them from the list for the sake of simplicity.		
- Issue linked to 334

[190226_add_new_project.pptx](https://github.com/openkfw/TruBudget/files/3002308/190226_add_new_project.pptx)

**Comment by mathiashoeld** [comment]
Name of source of finance - Done
Amount of source of finance - Done 
Currency of source of finance (from dropdown menu) - Done

Open Point: Donor name or State from dropdown menu

**Comment by mathiashoeld** [comment]
for open point, see: #226 
since other points are done, this issue will be closed.
